# Soc5044 Computational Sociology W6 Practicum - Data Collection Part 1

These teaching materials are adpated from [*Introduction to Cultural Analytics & Python*](https://melaniewalsh.github.io/Intro-Cultural-Analytics/welcome.html) (Walsh 2021) for the course "Soc5044 Computational Sociology" lectured at the sociology department of National Taiwan University by Dr. Chen-Shuo Hong.

In particular, this file uses the following chapters:
- "What is API", Chapter 4 Data Collection (Web Scraping, APIs, Social Media)
- "Song Genius API", Chapter 4 Data Collection (Web Scraping, APIs, Social Media)
- "Genius API", Chapter 4 Data Collection (Web Scraping, APIs, Social Media)
- "Song Lyrics Collection", Chapter 4 Data Collection (Web Scraping, APIs, Social Media)

> Melanie Walsh, Introduction to Cultural Analytics & Python, Version 1 (2021), https://doi.org/10.5281/zenodo.4411250.

Editor: Jun-Wei Liu (b09902009@ntu.edu.tw)

---

# 1. Application Programming Interfaces (APIs)

## What is an API? 
An API (Application Programming Interfaces) allows you to programmatically extract and interact with data under the hood of websites like Genius as well as other social networks, applications, and projects that make their data publicly available, such as Twitter and [The Smithsonian museums](https://www.si.edu/openaccess/devtools).

An API is something that a project or company explicitly designs for data-sharing purposes. Why do companies or projects go to all this trouble? One reason is that it helps to promote the use and further development of an application and its data. For example, Twitter wants other developers to use, integrate, and build upon Twitter tools and data. The Twitter API is the main conduit by which these developers can do so.

## Pros
Because APIs are explicitly designed for data-sharing purposes, working with an API is often a cleaner, more reliable, and more streamlined process than other ways of collecting internet data such as web scraping.

## Cons

One of the downsides is that the companies and projects that design the APIs get to decide exactly which kinds of data they want to share. \*Spoiler alert\* They often choose not to share their most lucrative and desirable data. For example, the Genius API does not provide access to lyrics data, and the Twitter API does not provide free access to tweets more than 14 days in the past. To get that Twitter data, you need to *pay* for special API access.

# 2. Song Genius API

In this lesson, we're going to use the Genius API to access data about Missy Elliott songs.

## API Keys

To use the Genius API, you need a special API key, specifically a "Client Access Token", which is kind of like a password. Many APIs require authentication keys to gain access to them. To get your necessary Genius API keys, you need to navigate to the following URL: [https://genius.com/api-clients](https://genius.com/api-clients).

<img src="../images/Genius-API.png" width=100% >

You'll be prompted to sign up for [a Genius account](https://genius.com/signup_or_login), which is required to gain API access. Signing up for a Genius account is free and easy. You just need a Genius nickname (which must be one word), an email address, and a password.

Once you're signed in, you should be taken to [https://genius.com/api-clients](https://genius.com/api-clients), where you need to click the button that says "New API Client."

<img src="../images/Genius-New-API.png" width=100% >

After clicking "New API Client," you'll be prompted to fill out a short form about the "App" that you need the Genius API for. You only need to fill out "App Name" and "App Website URL."

It doesn't really matter what you type in. You can simply put "Song Lyrics Project" for the "App Name" and the URL for our course website "https://melaniewalsh.github.io/Intro-Cultural-Analytics/" for the "App Website URL."

When you click "Save," you'll be given a series of API Keys: a "Client ID" and a "Client Secret." To generate your "Client Access Token," which is the API key that we'll be using in this notebook, you need to click "Generate Access Token".

Finally, copy and paste your "Client Access Token" into the quotation marks below, and run the cell to save your variable

In [ ]:
client_access_token = "INSERT YOUR CLIENT ACCESS TOKEN IN THESE QUOTATION MARKS"

### Protecting Your API Key

For this lesson, if you just copy and paste your Genius API key into your Jupyter notebook, everything should be fine. But that's actually not the best way of storing your API keys. If you published this notebook to GitHub, for example, other people might be able to read and use/steal your API key.

For this reason, it's best practice to keep your API keys away from your code, such as in another file. For example, I made a new Python file called "api_key.py" that contains just one variable `your_client_access_token = "MY API KEY"`, and I can import this variable into my notebook with `import api_key`.

In [ ]:
# import api_key

By importing this Python file/module, I get access to the variable `your_client_access_token` without ever explicitly typing my secret API token in this notebook. If I wanted to publish this notebook to GitHub, then I could ignore or leave out the "api_key.py" file that actually contains my Client Access Token.

In [ ]:
# client_access_token = api_key.your_client_access_token

## Making an API Request

Making an API request looks a lot like typing a specially-formatted URL. But instead of getting a rendered HTML web page in return, you get some data in return.

There are a few different ways that we can query the Genius API, all of which are discussed in the [Genius API documentation](https://docs.genius.com/#songs-h2). The way we're going to cover in this lesson is [the basic search](https://docs.genius.com/#search-h2), which allows you to get a bunch of Genius data about any artist or songs that you search for:

`http://api.genius.com/search?q={search_term}&access_token={client_access_token}`

Sticking with our Missy Elliott theme/obsession, we're going to search for Genius data about Missy Elliott.

First we're going to assign the string "Missy Elliott" to the variable `search_term`. Then we're going to make an f-string URL that contains the variables `search_term` and `client_access_token`. Note that if your `search_term` contains blanks, it has be replaced with the unicode of blank `%20` to make the URL valid.

In [ ]:
search_term = "Missy Elliott"

In [ ]:
genius_search_url = f"http://api.genius.com/search?q={search_term}&access_token={client_access_token}"
genius_search_url = genius_search_url.replace(" ", "%20")

This URL is basically all we need to make a Genius API request. Want proof? Run the cell below and print this URL, then copy and paste it into a new tab in your web browser.

In [13]:
print(genius_search_url)

http://api.genius.com/search?q=Missy%20Elliott&access_token=ExbB9TzY4eCNIoQ4zZBAFrnl6w5W7Mot8TrJNiBE3TUxC6Xedtg22htxOknpA2D3

It doesn't look pretty, but that's a bunch of Genius data about Missy Elliott!

We can programmatically do the same thing by again using the Python library `requests` with this URL. Instead of getting the `.text` of the response, as we did before, we're going to use `.json()`.

[JSON](https://www.w3schools.com/whatis/whatis_json.asp) is a data format that is commonly used by APIs. JSON data can be nested and contains key/value pairs, much like a Python dictionary.

In [14]:
import requests

In [15]:
response = requests.get(genius_search_url)
json_data = response.json()

The JSON data that we get from our Missy Elliott API query looks something like this:

In [16]:
json_data

{'meta': {'status': 200},
 'response': {'hits': [{'highlights': [],
    'index': 'song',
    'type': 'song',
    'result': {'annotation_count': 34,
     'api_path': '/songs/4176',
     'artist_names': 'Missy Elliott',
     'full_title': 'Work It by\xa0Missy\xa0Elliott',
     'header_image_thumbnail_url': 'https://images.genius.com/a54a36ef386a84ff0e689dc6d9cbdd18.300x300x1.jpg',
     'header_image_url': 'https://images.genius.com/a54a36ef386a84ff0e689dc6d9cbdd18.953x953x1.jpg',
     'id': 4176,
     'lyrics_owner_id': 6654,
     'lyrics_state': 'complete',
     'path': '/Missy-elliott-work-it-lyrics',
     'primary_artist_names': 'Missy Elliott',
     'pyongs_count': 42,
     'relationships_index_url': 'https://genius.com/Missy-elliott-work-it-sample',
     'release_date_components': {'year': 2002, 'month': 9, 'day': 1},
     'release_date_for_display': 'September 1, 2002',
     'release_date_with_abbreviated_month_for_display': 'Sep. 1, 2002',
     'song_art_image_thumbnail_url': 'https://images.genius.com/a54a36ef386a84ff0e689dc6d9cbdd18.300x300x1.jpg',
     'song_art_image_url': 'https://images.genius.com/a54a36ef386a84ff0e689dc6d9cbdd18.953x953x1.jpg',
     'stats': {'unreviewed_annotations': 3,
      'hot': False,
      'pageviews': 1481460},
     'title': 'Work It',
     'title_with_featured': 'Work It',
     'url': 'https://genius.com/Missy-elliott-work-it-lyrics',
     'featured_artists': [],
     'primary_artist': {'api_path': '/artists/1529',
      'header_image_url': 'https://images.genius.com/d91c82fa4ae2f1016fadc1c24fbbc59e.1000x333x1.jpg',
      'id': 1529,
      'image_url': 'https://images.genius.com/085828b7d79bf8cf068b1557ca7a5e4c.1000x1000x1.jpg',
      'is_meme_verified': False,
      'is_verified': False,
      'name': 'Missy Elliott',
      'url': 'https://genius.com/artists/Missy-elliott'},
     'primary_artists': [{'api_path': '/artists/1529',
       'header_image_url': 'https://images.genius.com/d91c82fa4ae2f1016fadc1c24fbbc59e.1000x333x1.jpg',
       'id': 1529,
       'image_url': 'https://images.genius.com/085828b7d79bf8cf068b1557ca7a5e4c.1000x1000x1.jpg',
       'is_meme_verified': False,
       'is_verified': False,
       'name': 'Missy Elliott',
       'url': 'https://genius.com/artists/Missy-elliott'}]}},
   {'highlights': [],
    'index': 'song',
    'type': 'song',
    'result': {'annotation_count': 28,
     'api_path': '/songs/2368201',
     'artist_names': 'Missy Elliott (Ft. Pharrell Williams)',
     'full_title': 'WTF (Where They From) by\xa0Missy\xa0Elliott (Ft.\xa0Pharrell\xa0Williams)',
     'header_image_thumbnail_url': 'https://images.rapgenius.com/a439d6d6020559ffe7c10f0d73722de1.300x300x1.jpg',
     'header_image_url': 'https://images.rapgenius.com/a439d6d6020559ffe7c10f0d73722de1.1000x1000x1.jpg',
     'id': 2368201,
     'lyrics_owner_id': 282633,
     'lyrics_state': 'complete',
     'path': '/Missy-elliott-wtf-where-they-from-lyrics',
     'primary_artist_names': 'Missy Elliott',
     'pyongs_count': 89,
     'relationships_index_url': 'https://genius.com/Missy-elliott-wtf-where-they-from-sample',
     'release_date_components': {'year': 2015, 'month': 11, 'day': 12},
     'release_date_for_display': 'November 12, 2015',
     'release_date_with_abbreviated_month_for_display': 'Nov. 12, 2015',
     'song_art_image_thumbnail_url': 'https://images.rapgenius.com/a439d6d6020559ffe7c10f0d73722de1.300x300x1.jpg',
     'song_art_image_url': 'https://images.rapgenius.com/a439d6d6020559ffe7c10f0d73722de1.1000x1000x1.jpg',
     'stats': {'unreviewed_annotations': 1, 'hot': False, 'pageviews': 298614},
     'title': 'WTF (Where They From)',
     'title_with_featured': 'WTF (Where They From) (Ft.\xa0Pharrell\xa0Williams)',
     'url': 'https://genius.com/Missy-elliott-wtf-where-they-from-lyrics',
     'featured_artists': [{'api_path': '/artists/110',
       'header_image_url': 'https://images.genius.com/6bb3ce5bd62c7acfc3a66798c4bbeb26.640x427x1.jpg',
       'id': 110,
       'image_url': 'https://images.genius.com/aa964e94a21e7b893801ed3a2bd389b8.1000x1000x1.jpg',
       'is_meme_verified': True,
       'is_verified': True,
       'name': 'Pharrell Williams',
       'url': 'https://genius.com/artists/Pharrell-williams',
       'iq': 732}],
     'primary_artist': {'api_path': '/artists/1529',
      'header_image_url': 'https://images.genius.com/d91c82fa4ae2f1016fadc1c24fbbc59e.1000x333x1.jpg',
      'id': 1529,
      'image_url': 'https://images.genius.com/085828b7d79bf8cf068b1557ca7a5e4c.1000x1000x1.jpg',
      'is_meme_verified': False,
      'is_verified': False,
      'name': 'Missy Elliott',
      'url': 'https://genius.com/artists/Missy-elliott'},
     'primary_artists': [{'api_path': '/artists/1529',
       'header_image_url': 'https://images.genius.com/d91c82fa4ae2f1016fadc1c24fbbc59e.1000x333x1.jpg',
       'id': 1529,
       'image_url': 'https://images.genius.com/085828b7d79bf8cf068b1557ca7a5e4c.1000x1000x1.jpg',
       'is_meme_verified': False,
       'is_verified': False,
       'name': 'Missy Elliott',
       'url': 'https://genius.com/artists/Missy-elliott'}]}},
   {'highlights': [],
    'index': 'song',
    'type': 'song',
    'result': {'annotation_count': 14,
     'api_path': '/songs/4640',
     'artist_names': 'Missy Elliott',
     'full_title': 'Get Ur Freak On by\xa0Missy\xa0Elliott',
     'header_image_thumbnail_url': 'https://images.genius.com/18baf13e5f41e15df357c3a85d673632.300x300x1.jpg',
     'header_image_url': 'https://images.genius.com/18baf13e5f41e15df357c3a85d673632.600x600x1.jpg',
     'id': 4640,
     'lyrics_owner_id': 1297,
     'lyrics_state': 'complete',
     'path': '/Missy-elliott-get-ur-freak-on-lyrics',
     'primary_artist_names': 'Missy Elliott',
     'pyongs_count': 19,
     'relationships_index_url': 'https://genius.com/Missy-elliott-get-ur-freak-on-sample',
     'release_date_components': {'year': 2001, 'month': 3, 'day': 6},
     'release_date_for_display': 'March 6, 2001',
     'release_date_with_abbreviated_month_for_display': 'Mar. 6, 2001',
     'song_art_image_thumbnail_url': 'https://images.genius.com/18baf13e5f41e15df357c3a85d673632.300x300x1.jpg',
     'song_art_image_url': 'https://images.genius.com/18baf13e5f41e15df357c3a85d673632.600x600x1.jpg',
     'stats': {'unreviewed_annotations': 0, 'hot': False, 'pageviews': 230192},
     'title': 'Get Ur Freak On',
     'title_with_featured': 'Get Ur Freak On',
     'url': 'https://genius.com/Missy-elliott-get-ur-freak-on-lyrics',
     'featured_artists': [],
     'primary_artist': {'api_path': '/artists/1529',
      'header_image_url': 'https://images.genius.com/d91c82fa4ae2f1016fadc1c24fbbc59e.1000x333x1.jpg',
      'id': 1529,
      'image_url': 'https://images.genius.com/085828b7d79bf8cf068b1557ca7a5e4c.1000x1000x1.jpg',
      'is_meme_verified': False,
      'is_verified': False,
      'name': 'Missy Elliott',
      'url': 'https://genius.com/artists/Missy-elliott'},
     'primary_artists': [{'api_path': '/artists/1529',
       'header_image_url': 'https://images.genius.com/d91c82fa4ae2f1016fadc1c24fbbc59e.1000x333x1.jpg',
       'id': 1529,
       'image_url': 'https://images.genius.com/085828b7d79bf8cf068b1557ca7a5e4c.1000x1000x1.jpg',
       'is_meme_verified': False,
       'is_verified': False,
       'name': 'Missy Elliott',
       'url': 'https://genius.com/artists/Missy-elliott'}]}},
   {'highlights': [],
    'index': 'song',
    'type': 'song',
    'result': {'annotation_count': 6,
     'api_path': '/songs/33158',
     'artist_names': 'Missy Elliott (Ft. Ciara & Fatman Scoop)',
     'full_title': 'Lose Control by\xa0Missy\xa0Elliott (Ft.\xa0Ciara & Fatman\xa0Scoop)',
     'header_image_thumbnail_url': 'https://images.genius.com/51639e476eac5cb5bed5794c023763ff.300x303x1.jpg',
     'header_image_url': 'https://images.genius.com/51639e476eac5cb5bed5794c023763ff.700x707x1.jpg',
     'id': 33158,
     'lyrics_owner_id': 50,
     'lyrics_state': 'complete',
     'path': '/Missy-elliott-lose-control-lyrics',
     'primary_artist_names': 'Missy Elliott',
     'pyongs_count': 11,
     'relationships_index_url': 'https://genius.com/Missy-elliott-lose-control-sample',
     'release_date_components': {'year': 2005, 'month': 5, 'day': 27},
     'release_date_for_display': 'May 27, 2005',
     'release_date_with_abbreviated_month_for_display': 'May 27, 2005',
     'song_art_image_thumbnail_url': 'https://images.genius.com/51639e476eac5cb5bed5794c023763ff.300x303x1.jpg',
     'song_art_image_url': 'https://images.genius.com/51639e476eac5cb5bed5794c023763ff.700x707x1.jpg',
     'stats': {'unreviewed_annotations': 2, 'hot': False, 'pageviews': 152292},
     'title': 'Lose Control',
     'title_with_featured': 'Lose Control (Ft.\xa0Ciara & Fatman\xa0Scoop)',
     'url': 'https://genius.com/Missy-elliott-lose-control-lyrics',
     'featured_artists': [{'api_path': '/artists/3516',
       'header_image_url': 'https://images.genius.com/c6668ff096c94f8ce5a42becf4d65277.576x576x1.jpg',
       'id': 3516,
       'image_url': 'https://images.genius.com/c6668ff096c94f8ce5a42becf4d65277.576x576x1.jpg',
       'is_meme_verified': False,
       'is_verified': False,
       'name': 'Fatman Scoop',
       'url': 'https://genius.com/artists/Fatman-scoop'},
      {'api_path': '/artists/1630',
       'header_image_url': 'https://images.genius.com/8636c8aad8dfba446f8f0a3cbb8962aa.1000x245x1.png',
       'id': 1630,
       'image_url': 'https://images.genius.com/e923a5d22355e8946f06bacc8661f0c1.640x640x1.jpg',
       'is_meme_verified': False,
       'is_verified': False,
       'name': 'Ciara',
       'url': 'https://genius.com/artists/Ciara'}],
     'primary_artist': {'api_path': '/artists/1529',
      'header_image_url': 'https://images.genius.com/d91c82fa4ae2f1016fadc1c24fbbc59e.1000x333x1.jpg',
      'id': 1529,
      'image_url': 'https://images.genius.com/085828b7d79bf8cf068b1557ca7a5e4c.1000x1000x1.jpg',
      'is_meme_verified': False,
      'is_verified': False,
      'name': 'Missy Elliott',
      'url': 'https://genius.com/artists/Missy-elliott'},
     'primary_artists': [{'api_path': '/artists/1529',
       'header_image_url': 'https://images.genius.com/d91c82fa4ae2f1016fadc1c24fbbc59e.1000x333x1.jpg',
       'id': 1529,
       'image_url': 'https://images.genius.com/085828b7d79bf8cf068b1557ca7a5e4c.1000x1000x1.jpg',
       'is_meme_verified': False,
       'is_verified': False,
       'name': 'Missy Elliott',
       'url': 'https://genius.com/artists/Missy-elliott'}]}},
   {'highlights': [],
    'index': 'song',
    'type': 'song',
    'result': {'annotation_count': 42,
     'api_path': '/songs/4173',
     'artist_names': 'Missy Elliott (Ft. Ludacris)',
     'full_title': 'Gossip Folks by\xa0Missy\xa0Elliott (Ft.\xa0Ludacris)',
     'header_image_thumbnail_url': 'https://images.genius.com/206153c53d05804677e236aa2ae4eb45.300x300x1.jpg',
     'header_image_url': 'https://images.genius.com/206153c53d05804677e236aa2ae4eb45.600x600x1.jpg',
     'id': 4173,
     'lyrics_owner_id': 6654,
     'lyrics_state': 'complete',
     'path': '/Missy-elliott-gossip-folks-lyrics',
     'primary_artist_names': 'Missy Elliott',
     'pyongs_count': 8,
     'relationships_index_url': 'https://genius.com/Missy-elliott-gossip-folks-sample',
     'release_date_components': {'year': 2002, 'month': 11, 'day': 12},
     'release_date_for_display': 'November 12, 2002',
     'release_date_with_abbreviated_month_for_display': 'Nov. 12, 2002',
     'song_art_image_thumbnail_url': 'https://images.genius.com/206153c53d05804677e236aa2ae4eb45.300x300x1.jpg',
     'song_art_image_url': 'https://images.genius.com/206153c53d05804677e236aa2ae4eb45.600x600x1.jpg',
     'stats': {'unreviewed_annotations': 0, 'hot': False, 'pageviews': 145116},
     'title': 'Gossip Folks',
     'title_with_featured': 'Gossip Folks (Ft.\xa0Ludacris)',
     'url': 'https://genius.com/Missy-elliott-gossip-folks-lyrics',
     'featured_artists': [{'api_path': '/artists/111',
       'header_image_url': 'https://images.genius.com/5370c6df2341b7638b5277019218d014.640x798x1.jpg',
       'id': 111,
       'image_url': 'https://images.genius.com/64c5f330eee25004ac945e11bdd8279b.640x640x1.jpg',
       'is_meme_verified': False,
       'is_verified': False,
       'name': 'Ludacris',
       'url': 'https://genius.com/artists/Ludacris'}],
     'primary_artist': {'api_path': '/artists/1529',
      'header_image_url': 'https://images.genius.com/d91c82fa4ae2f1016fadc1c24fbbc59e.1000x333x1.jpg',
      'id': 1529,
      'image_url': 'https://images.genius.com/085828b7d79bf8cf068b1557ca7a5e4c.1000x1000x1.jpg',
      'is_meme_verified': False,
      'is_verified': False,
      'name': 'Missy Elliott',
      'url': 'https://genius.com/artists/Missy-elliott'},
     'primary_artists': [{'api_path': '/artists/1529',
       'header_image_url': 'https://images.genius.com/d91c82fa4ae2f1016fadc1c24fbbc59e.1000x333x1.jpg',
       'id': 1529,
       'image_url': 'https://images.genius.com/085828b7d79bf8cf068b1557ca7a5e4c.1000x1000x1.jpg',
       'is_meme_verified': False,
       'is_verified': False,
       'name': 'Missy Elliott',
       'url': 'https://genius.com/artists/Missy-elliott'}]}},
   {'highlights': [],
    'index': 'song',
    'type': 'song',
    'result': {'annotation_count': 16,
     'api_path': '/songs/128',
     'artist_names': 'Missy Elliott',
     'full_title': 'The Rain (Supa Dupa Fly) by\xa0Missy\xa0Elliott',
     'header_image_thumbnail_url': 'https://images.genius.com/a1543159342cd360256c12b42185771f.300x308x1.jpg',
     'header_image_url': 'https://images.genius.com/a1543159342cd360256c12b42185771f.975x1000x1.jpg',
     'id': 128,
     'lyrics_owner_id': 4619460,
     'lyrics_state': 'complete',
     'path': '/Missy-elliott-the-rain-supa-dupa-fly-lyrics',
     'primary_artist_names': 'Missy Elliott',
     'pyongs_count': 8,
     'relationships_index_url': 'https://genius.com/Missy-elliott-the-rain-supa-dupa-fly-sample',
     'release_date_components': {'year': 1997, 'month': 5, 'day': 20},
     'release_date_for_display': 'May 20, 1997',
     'release_date_with_abbreviated_month_for_display': 'May 20, 1997',
     'song_art_image_thumbnail_url': 'https://images.genius.com/a1543159342cd360256c12b42185771f.300x308x1.jpg',
     'song_art_image_url': 'https://images.genius.com/a1543159342cd360256c12b42185771f.975x1000x1.jpg',
     'stats': {'unreviewed_annotations': 0, 'hot': False, 'pageviews': 134138},
     'title': 'The Rain (Supa Dupa Fly)',
     'title_with_featured': 'The Rain (Supa Dupa Fly)',
     'url': 'https://genius.com/Missy-elliott-the-rain-supa-dupa-fly-lyrics',
     'featured_artists': [],
     'primary_artist': {'api_path': '/artists/1529',
      'header_image_url': 'https://images.genius.com/d91c82fa4ae2f1016fadc1c24fbbc59e.1000x333x1.jpg',
      'id': 1529,
      'image_url': 'https://images.genius.com/085828b7d79bf8cf068b1557ca7a5e4c.1000x1000x1.jpg',
      'is_meme_verified': False,
      'is_verified': False,
      'name': 'Missy Elliott',
      'url': 'https://genius.com/artists/Missy-elliott'},
     'primary_artists': [{'api_path': '/artists/1529',
       'header_image_url': 'https://images.genius.com/d91c82fa4ae2f1016fadc1c24fbbc59e.1000x333x1.jpg',
       'id': 1529,
       'image_url': 'https://images.genius.com/085828b7d79bf8cf068b1557ca7a5e4c.1000x1000x1.jpg',
       'is_meme_verified': False,
       'is_verified': False,
       'name': 'Missy Elliott',
       'url': 'https://genius.com/artists/Missy-elliott'}]}},
   {'highlights': [],
    'index': 'song',
    'type': 'song',
    'result': {'annotation_count': 9,
     'api_path': '/songs/2967124',
     'artist_names': 'Missy Elliott (Ft. Cainon Lamb)',
     'full_title': "I'm Better by\xa0Missy\xa0Elliott (Ft.\xa0Cainon\xa0Lamb)",
     'header_image_thumbnail_url': 'https://images.genius.com/609afe10820cce09ce9e3c768518c63c.300x300x1.jpg',
     'header_image_url': 'https://images.genius.com/609afe10820cce09ce9e3c768518c63c.600x600x1.jpg',
     'id': 2967124,
     'lyrics_owner_id': 3075478,
     'lyrics_state': 'complete',
     'path': '/Missy-elliott-im-better-lyrics',
     'primary_artist_names': 'Missy Elliott',
     'pyongs_count': 13,
     'relationships_index_url': 'https://genius.com/Missy-elliott-im-better-sample',
     'release_date_components': {'year': 2017, 'month': 1, 'day': 26},
     'release_date_for_display': 'January 26, 2017',
     'release_date_with_abbreviated_month_for_display': 'Jan. 26, 2017',
     'song_art_image_thumbnail_url': 'https://images.genius.com/609afe10820cce09ce9e3c768518c63c.300x300x1.jpg',
     'song_art_image_url': 'https://images.genius.com/609afe10820cce09ce9e3c768518c63c.600x600x1.jpg',
     'stats': {'unreviewed_annotations': 0, 'hot': False, 'pageviews': 114407},
     'title': 'I’m Better',
     'title_with_featured': "I'm Better (Ft.\xa0Cainon\xa0Lamb)",
     'url': 'https://genius.com/Missy-elliott-im-better-lyrics',
     'featured_artists': [{'api_path': '/artists/305112',
       'header_image_url': 'https://images.genius.com/b0bf9bf9be2df21ab3f6a45cd9cad67e.299x299x1.jpg',
       'id': 305112,
       'image_url': 'https://images.genius.com/b0bf9bf9be2df21ab3f6a45cd9cad67e.299x299x1.jpg',
       'is_meme_verified': False,
       'is_verified': False,
       'name': 'Cainon Lamb',
       'url': 'https://genius.com/artists/Cainon-lamb'}],
     'primary_artist': {'api_path': '/artists/1529',
      'header_image_url': 'https://images.genius.com/d91c82fa4ae2f1016fadc1c24fbbc59e.1000x333x1.jpg',
      'id': 1529,
      'image_url': 'https://images.genius.com/085828b7d79bf8cf068b1557ca7a5e4c.1000x1000x1.jpg',
      'is_meme_verified': False,
      'is_verified': False,
      'name': 'Missy Elliott',
      'url': 'https://genius.com/artists/Missy-elliott'},
     'primary_artists': [{'api_path': '/artists/1529',
       'header_image_url': 'https://images.genius.com/d91c82fa4ae2f1016fadc1c24fbbc59e.1000x333x1.jpg',
       'id': 1529,
       'image_url': 'https://images.genius.com/085828b7d79bf8cf068b1557ca7a5e4c.1000x1000x1.jpg',
       'is_meme_verified': False,
       'is_verified': False,
       'name': 'Missy Elliott',
       'url': 'https://genius.com/artists/Missy-elliott'}]}},
   {'highlights': [],
    'index': 'song',
    'type': 'song',
    'result': {'annotation_count': 19,
     'api_path': '/songs/4671',
     'artist_names': 'Missy Elliott (Ft. Ludacris & Trina)',
     'full_title': 'One Minute Man (Video Remix) by\xa0Missy\xa0Elliott (Ft.\xa0Ludacris & Trina)',
     'header_image_thumbnail_url': 'https://images.genius.com/a94eaf3c98a7134cb546ebf9e6d2b991.300x300x1.jpg',
     'header_image_url': 'https://images.genius.com/a94eaf3c98a7134cb546ebf9e6d2b991.953x953x1.jpg',
     'id': 4671,
     'lyrics_owner_id': 7299,
     'lyrics_state': 'complete',
     'path': '/Missy-elliott-one-minute-man-video-remix-lyrics',
     'primary_artist_names': 'Missy Elliott',
     'pyongs_count': 6,
     'relationships_index_url': 'https://genius.com/Missy-elliott-one-minute-man-video-remix-sample',
     'release_date_components': {'year': 2001, 'month': 6, 'day': 22},
     'release_date_for_display': 'June 22, 2001',
     'release_date_with_abbreviated_month_for_display': 'Jun. 22, 2001',
     'song_art_image_thumbnail_url': 'https://images.genius.com/a94eaf3c98a7134cb546ebf9e6d2b991.300x300x1.jpg',
     'song_art_image_url': 'https://images.genius.com/a94eaf3c98a7134cb546ebf9e6d2b991.953x953x1.jpg',
     'stats': {'unreviewed_annotations': 7, 'hot': False, 'pageviews': 78526},
     'title': 'One Minute Man (Video Remix)',
     'title_with_featured': 'One Minute Man (Video Remix) (Ft.\xa0Ludacris & Trina)',
     'url': 'https://genius.com/Missy-elliott-one-minute-man-video-remix-lyrics',
     'featured_artists': [{'api_path': '/artists/117',
       'header_image_url': 'https://images.genius.com/cf9fb6a21b7232aa1b28cd4c0543b4ff.550x271x1.jpg',
       'id': 117,

We can index this data (again, like a Python dictionary) and look at the first "hit" about Missy Elliott from Genius.com.

In [17]:
json_data['response']['hits'][0]

{'highlights': [],
 'index': 'song',
 'type': 'song',
 'result': {'annotation_count': 34,
  'api_path': '/songs/4176',
  'artist_names': 'Missy Elliott',
  'full_title': 'Work It by\xa0Missy\xa0Elliott',
  'header_image_thumbnail_url': 'https://images.genius.com/a54a36ef386a84ff0e689dc6d9cbdd18.300x300x1.jpg',
  'header_image_url': 'https://images.genius.com/a54a36ef386a84ff0e689dc6d9cbdd18.953x953x1.jpg',
  'id': 4176,
  'lyrics_owner_id': 6654,
  'lyrics_state': 'complete',
  'path': '/Missy-elliott-work-it-lyrics',
  'primary_artist_names': 'Missy Elliott',
  'pyongs_count': 42,
  'relationships_index_url': 'https://genius.com/Missy-elliott-work-it-sample',
  'release_date_components': {'year': 2002, 'month': 9, 'day': 1},
  'release_date_for_display': 'September 1, 2002',
  'release_date_with_abbreviated_month_for_display': 'Sep. 1, 2002',
  'song_art_image_thumbnail_url': 'https://images.genius.com/a54a36ef386a84ff0e689dc6d9cbdd18.300x300x1.jpg',
  'song_art_image_url': 'https://images.genius.com/a54a36ef386a84ff0e689dc6d9cbdd18.953x953x1.jpg',
  'stats': {'unreviewed_annotations': 3, 'hot': False, 'pageviews': 1481460},
  'title': 'Work It',
  'title_with_featured': 'Work It',
  'url': 'https://genius.com/Missy-elliott-work-it-lyrics',
  'featured_artists': [],
  'primary_artist': {'api_path': '/artists/1529',
   'header_image_url': 'https://images.genius.com/d91c82fa4ae2f1016fadc1c24fbbc59e.1000x333x1.jpg',
   'id': 1529,
   'image_url': 'https://images.genius.com/085828b7d79bf8cf068b1557ca7a5e4c.1000x1000x1.jpg',
   'is_meme_verified': False,
   'is_verified': False,
   'name': 'Missy Elliott',
   'url': 'https://genius.com/artists/Missy-elliott'},
  'primary_artists': [{'api_path': '/artists/1529',
    'header_image_url': 'https://images.genius.com/d91c82fa4ae2f1016fadc1c24fbbc59e.1000x333x1.jpg',
    'id': 1529,
    'image_url': 'https://images.genius.com/085828b7d79bf8cf068b1557ca7a5e4c.1000x1000x1.jpg',
    'is_meme_verified': False,
    'is_verified': False,
    'name': 'Missy Elliott',
    'url': 'https://genius.com/artists/Missy-elliott'}]}}

We can tell that this data describes the song "Work It" and contains other information about the song, such as its number of Genius annotations, its number of web page views, and links to images of its album cover.

## Looping Through JSON Data

### Get Song Titles

In [18]:
for song in json_data['response']['hits']:
    print(song['result']['full_title'])

Work It by Missy Elliott
WTF (Where They From) by Missy Elliott (Ft. Pharrell Williams)
Get Ur Freak On by Missy Elliott
Lose Control by Missy Elliott (Ft. Ciara & Fatman Scoop)
Gossip Folks by Missy Elliott (Ft. Ludacris)
The Rain (Supa Dupa Fly) by Missy Elliott
I'm Better by Missy Elliott (Ft. Cainon Lamb)
One Minute Man (Video Remix) by Missy Elliott (Ft. Ludacris & Trina)
Hot Boyz (Remix) by Missy Elliott (Ft. Eve, Lil' Mo, Nas & Q-Tip)
Bomb Intro / Pass That Dutch by Missy Elliott

### Get Song Tiles and Page View Counts

In [19]:
for song in json_data['response']['hits']:
    print(song['result']['full_title'], song['result']['stats']['pageviews'])

Work It by Missy Elliott 1481460
WTF (Where They From) by Missy Elliott (Ft. Pharrell Williams) 298614
Get Ur Freak On by Missy Elliott 230192
Lose Control by Missy Elliott (Ft. Ciara & Fatman Scoop) 152292
Gossip Folks by Missy Elliott (Ft. Ludacris) 145116
The Rain (Supa Dupa Fly) by Missy Elliott 134138
I'm Better by Missy Elliott (Ft. Cainon Lamb) 114407
One Minute Man (Video Remix) by Missy Elliott (Ft. Ludacris & Trina) 78526
Hot Boyz (Remix) by Missy Elliott (Ft. Eve, Lil' Mo, Nas & Q-Tip) 67363
Bomb Intro / Pass That Dutch by Missy Elliott 62967

### Transform Song Titles and Page View Counts into a DataFrame

We can loop through this data, append it into a list, and then transform that list into a Pandas dataframe by calling `pd.DataFrame()`

In [20]:
import pandas as pd

:::{admonition} Pandas Review
:class: pandasreview
 Do you need a refresher or introduction to the Python data analysis library Pandas? Be sure to check out <a href="https://melaniewalsh.github.io/Intro-Cultural-Analytics/Data-Analysis/Pandas-Basics-Part1.html"> Pandas Basics (1-3) </a> in this textbook!
    
:::

In [21]:
missy_songs = []
for song in json_data['response']['hits']:
    missy_songs.append([song['result']['full_title'], song['result']['stats']['pageviews']])
    
#Make a Pandas dataframe from a list
missy_df = pd.DataFrame(missy_songs)
missy_df.columns = ['song_title', 'page_views']
missy_df

                                          song_title  page_views
0                           Work It by Missy Elliott     1481460
1  WTF (Where They From) by Missy Elliott (Ft. Ph...      298614
2                   Get Ur Freak On by Missy Elliott      230192
3  Lose Control by Missy Elliott (Ft. Ciara & Fat...      152292
4       Gossip Folks by Missy Elliott (Ft. Ludacris)      145116
5          The Rain (Supa Dupa Fly) by Missy Elliott      134138
6      I'm Better by Missy Elliott (Ft. Cainon Lamb)      114407
7  One Minute Man (Video Remix) by Missy Elliott ...       78526
8  Hot Boyz (Remix) by Missy Elliott (Ft. Eve, Li...       67363
9      Bomb Intro / Pass That Dutch by Missy Elliott       62967

## Transform Song Titles, Page View Counts, & Album Covers into a DataFrame

Just for fun, we can do the same thing but also add links to images of Missy Elliott's album art—and we can actually display those images, too!

To display images in a Pandas dataframe, you need to run `from IPython.core.display import HTML` and make the function `get_image_html()`. We're going to take the image URLs and make them into HTML objects.

In [22]:
from IPython.core.display import HTML

In [23]:
def get_image_html(link):
    image_html = f"<img src='{link}' width='500px'>"
    return image_html

In [24]:
missy_songs = []
for song in json_data['response']['hits']:
    missy_songs.append([song['result']['full_title'], song['result']['stats']['pageviews'], song['result']['song_art_image_url']])
    
missy_df = pd.DataFrame(missy_songs)
missy_df.columns = ['song_title', 'page_views','album_cover_url']

#Use the function get_image_html()
missy_df['album_cover'] = missy_df['album_cover_url'].apply(get_image_html)
missy_df

,song_title,page_views,album_cover_url,album_cover
0,Work It by Missy Elliott,1481460,https://images.genius.com/a54a36ef386a84ff0e68...,<img src='https://images.genius.com/a54a36ef38...
1,WTF (Where They From) by Missy Elliott (Ft. Ph...,298614,https://images.rapgenius.com/a439d6d6020559ffe...,<img src='https://images.rapgenius.com/a439d6d...
2,Get Ur Freak On by Missy Elliott,230192,https://images.genius.com/18baf13e5f41e15df357...,<img src='https://images.genius.com/18baf13e5f...
3,Lose Control by Missy Elliott (Ft. Ciara & Fat...,152292,https://images.genius.com/51639e476eac5cb5bed5...,<img src='https://images.genius.com/51639e476e...
4,Gossip Folks by Missy Elliott (Ft. Ludacris),145116,https://images.genius.com/206153c53d05804677e2...,<img src='https://images.genius.com/206153c53d...
5,The Rain (Supa Dupa Fly) by Missy Elliott,134138,https://images.genius.com/a1543159342cd360256c...,<img src='https://images.genius.com/a154315934...
6,I'm Better by Missy Elliott (Ft. Cainon Lamb),114407,https://images.genius.com/609afe10820cce09ce9e...,<img src='https://images.genius.com/609afe1082...
7,One Minute Man (Video Remix) by Missy Elliott ...,78526,https://images.genius.com/a94eaf3c98a7134cb546...,<img src='https://images.genius.com/a94eaf3c98...
8,"Hot Boyz (Remix) by Missy Elliott (Ft. Eve, Li...",67363,https://images.genius.com/2f13ef58a8d5efe0b1a4...,<img src='https://images.genius.com/2f13ef58a8...
9,Bomb Intro / Pass That Dutch by Missy Elliott,62967,https://images.genius.com/5d11feb4defc574944d2...,<img src='https://images.genius.com/5d11feb4de...

If we call `HTML()` on our dataframe and add the method `.to_html(escape=False)` to the dataframe, then it should display the dataframe with viewable images.

In [25]:
HTML(missy_df[['album_cover', 'page_views', 'song_title']].to_html(escape=False))

## Your Turn!

Replace "Phoebe Bridgers" with any artist/musician of your choosing and run the following cells.

In [26]:
search_term = "Phoebe Bridgers"

In [27]:
genius_search_url = f"http://api.genius.com/search?q={search_term}&access_token={client_access_token}"
genius_search_url = genius_search_url.replace(" ", "%20")

In [28]:
response = requests.get(genius_search_url)
json_data = response.json()

In [29]:
songs = []
for song in json_data['response']['hits']:
    songs.append((song['result']['full_title'], song['result']['stats']['pageviews'], song['result']['song_art_image_url']))
    
artist_df = pd.DataFrame(songs)
artist_df.columns = ['song_title', 'page_views', 'album_cover_url']

artist_df['album_cover'] = artist_df['album_cover_url'].apply(get_image_html)
HTML(artist_df[['album_cover', 'page_views', 'song_title']].to_html(escape=False))

# 3. Song Lyrics Collection

In this lesson, we're going to use a Python package called [LyricsGenius](https://github.com/johnwmillr/LyricsGenius) to collect song lyrics about any artist and album.

## API Wrappers
An API wrapper is a package that makes an API easier to use and/or extends the API's functionality. A data scientist named John Miller wrote a Python package called [LyricsGenius,](https://github.com/johnwmillr/LyricsGenius) which makes working with the Genius API easier and adds functionality not offered by the Genius API.

Remember when I said that companies typically don't offer access to their most lucrative data? Well, the Genius API doesn't offer you a way to get access to song lyrics. To solve this problem, LyricsGenius combines the Genius API with the web scraping library BeautifulSoup to get and save song lyrics.

## Install the Package

To install LyricsGenius (and get the most updated version from GitHub), run:

In [30]:
!pip install git+https://github.com/johnwmillr/LyricsGenius.git

Defaulting to user installation because normal site-packages is not writeable
Collecting git+https://github.com/johnwmillr/LyricsGenius.git
  Cloning https://github.com/johnwmillr/LyricsGenius.git to /tmp/pip-req-build-v70p4yhf
  Running command git clone --filter=blob:none --quiet https://github.com/johnwmillr/LyricsGenius.git /tmp/pip-req-build-v70p4yhf
  Resolved https://github.com/johnwmillr/LyricsGenius.git to commit 7635cff7af35bfa5b6e8ec36ca6921faf7014cc3
  Preparing metadata (setup.py) ... done
Collecting beautifulsoup4>=4.6.0
  Downloading beautifulsoup4-4.13.3-py3-none-any.whl (186 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 186.0/186.0 KB 915.4 kB/s eta 0:00:00a 0:00:01
Requirement already satisfied: requests>=2.20.0 in /home/letuvertia/.local/lib/python3.10/site-packages (from lyricsgenius==3.2.0) (2.32.3)
Collecting soupsieve>1.2
  Downloading soupsieve-2.6-py3-none-any.whl (36 kB)
Requirement already satisfied: typing-extensions>=4.0.0 in /home/letuvertia/.local/lib/python3.10/site-packages (from beautifulsoup4>=4.6.0->lyricsgenius==3.2.0) (4.11.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/lib/python3/dist-packages (from requests>=2.20.0->lyricsgenius==3.2.0) (2020.6.20)
Requirement already satisfied: charset-normalizer<4,>=2 in /home/letuvertia/.local/lib/python3.10/site-packages (from requests>=2.20.0->lyricsgenius==3.2.0) (3.3.2)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/lib/python3/dist-packages (from requests>=2.20.0->lyricsgenius==3.2.0) (1.26.5)
Requirement already satisfied: idna<4,>=2.5 in /usr/lib/python3/dist-packages (from requests>=2.20.0->lyricsgenius==3.2.0) (3.3)
Building wheels for collected packages: lyricsgenius
  Building wheel for lyricsgenius (setup.py) ... done
  Created wheel for lyricsgenius: filename=lyricsgenius-3.2.0-py3-none-any.whl size=45066 sha256=6ecf8f40cc4c107379b8f08c30ea7615c01fd533e8faac1e9894d5a159254fd2
  Stored in directory: /tmp/pip-ephem-wheel-cache-u7js4948/wheels/a2/6d/80/1297c611c6dc8bd51f83121a1e209257591bc9a0486bd2e279
Successfully built lyricsgenius
Installing collected packages: soupsieve, beautifulsoup4, lyricsgenius
Successfully installed beautifulsoup4-4.13.3 lyricsgenius-3.2.0 soupsieve-2.6

Copy and paste your Genius "Client Access Token" into the quotation marks below, and run the cell to save your variable :

In [ ]:
client_access_token = "INSERT YOUR CLIENT ACCESS TOKEN IN THESE QUOTATION MARKS"

Import and initialize LyricsGenius

In [32]:
import lyricsgenius
LyricsGenius = lyricsgenius.Genius(client_access_token)

## Get Songs and Lyrics By a Specific Artist

To get the top songs and song lyrics from a specific artist you can use the method `.search_artist()`:

In [33]:
artist = LyricsGenius.search_artist("Missy Elliott", max_songs=6)

Searching for songs by Missy Elliott...

Song 1: "Work It"
Song 2: "WTF (Where They From)"
Song 3: "Get Ur Freak On"
Song 4: "Lose Control"
Song 5: "Gossip Folks"
Song 6: "The Rain (Supa Dupa Fly)"

Reached user-specified song limit (6).
Done. Found 6 songs.

To access the song titles, you can run `artist.songs`:

In [34]:
artist.songs

[Song(id, artist, ...),
 Song(id, artist, ...),
 Song(id, artist, ...),
 Song(id, artist, ...),
 Song(id, artist, ...),
 Song(id, artist, ...)]

Inside each of those songs, LyricsGenius has already saved the song lyrics. You can access these lyrics by looping through `artist.songs` and pulling out `song.lyrics`:

In [35]:
for song in artist.songs:
    print(song.lyrics)

127 ContributorsWork It Lyrics[Intro]
DJ, please pick up your phone, I'm on the request line
This is a Missy Elliott one-time exclusive (C'mon)

[Chorus]
Is it worth it? Let me work it
I put my thing down, flip it and reverse it
​ti esrever dna ti pilf ,nwod gniht ym tuP
​ti esrever dna ti pilf ,nwod gniht ym tuP
If you got a big— let me search ya
And find out how hard I gotta work ya
​ti esrever dna ti pilf ,nwod gniht ym tuP
​ti esrever dna ti pilf ,nwod gniht ym tuP (C'mon)

[Verse 1]
I'd like to get to know ya so I could show ya
Put the pussy on ya like I told ya
Give me all your numbers so I can phone ya
Your girl acting stank, then call me over
Not on the bed, lay me on your sofa
Call before you come, I need to shave my chocha
You do or you don't or you will or won't ya?
Go downtown and eat it like a vulture
See my hips and my tips, don't ya?
See my ass and my lips, don't ya?
Lost a few pounds and my waist for ya
This the kind of beat that go ra-ta-ta
Ra-ta-ta-ta-ta-ta-ta-ta-ta-ta
Sex me so good I say blah-blah-blah
Work it, I need a glass of water
Boy, oh boy, it's good to know ya (C'mon)
See Missy Elliott LiveGet tickets as low as $236You might also like[Chorus]
Is it worth it? Let me work it
I put my thing down, flip it and reverse it
​ti esrever dna ti pilf ,nwod gniht ym tuP
​ti esrever dna ti pilf ,nwod gniht ym tuP
If you got a big— let me search ya
And find out how hard I gotta work ya
​ti esrever dna ti pilf ,nwod gniht ym tuP
​ti esrever dna ti pilf ,nwod gniht ym tuP (C'mon)

[Verse 2]
If you a fly gal, get your nails done
Get a pedicure, get your hair did
Boy, lift it up, let's make a toast-a
Let's get drunk, that's gonna bring us closer (Okay)
Don't I look like a Halle Berry poster?
See the Belvedere playing tricks on ya (Ah)
Girlfriend wanna be like me, never
You won't find a bitch that's even better (Ah)
I make you hot as Las Vegas weather
Listen up close while I take it backwards
​sdrawkcab ti ekat ot ekil yssiM yaw eht hctaW
I'm not a prostitute, but I could give you what you want
I love your braids and your mouth full of fronts
Love the way my ass go ba-bum-bum-bum-bum (Huh)
Keep your eyes on my ba-bum-bum-bum-bum-bum (Okay)
You think you can handle this? Ga-dunk-a-dunk-dunk (Woo)
Take my thong off and my ass go boom (Ugh)
Cut the lights on so you see what I could do (C'mon)
[Chorus]
Is it worth it? Let me work it
I put my thing down, flip it and reverse it
​ti esrever dna ti pilf ,nwod gniht ym tuP
​ti esrever dna ti pilf ,nwod gniht ym tuP (Ooh)
If you got a big— let me search ya
And find out how hard I gotta work ya
​ti esrever dna ti pilf ,nwod gniht ym tuP (Huh)
​ti esrever dna ti pilf ,nwod gniht ym tuP (C'mon, c'mon)

[Bridge]
Boys, boys, all type of boys
Black, white, Puerto Rican, Chinese boys (C'mon)
Why-thai, thai-o-toy-o-thai-thai
Why-thai, thai-o-toy-o-thai-thai (C'mon)
Girls, girls, get that cash
If it's nine to five or shaking your ass (Aha)
Ain't no shame, ladies do your thing (C'mon)
Just make sure you ahead of the game

[Verse 3]
Just 'cause I got a lot of fame super
Prince couldn't get me change my name, papa
Kunta Kinte a slave again, no sir
Picture Blacks saying, “Oh yes-a, massa”
Picture Lil' Kim dating a pastor
Minute man, Big Red could outlast ya
Who is the best? I don't have to ask ya
When I come out, you won't even matter (Ugh)
Why you act dumb like, yeah, duh?
So you act dumb like, uh, duh
As the drummer boy go ba-rom-pop-pom-pom (Ooh)
Give you some-some-some of this cinna-bun (C'mon)
[Chorus]
Is it worth it? Let me work it
I put my thing down, flip it and reverse it
​ti esrever dna ti pilf ,nwod gniht ym tuP
​ti esrever dna ti pilf ,nwod gniht ym tuP (Ooh)
If you got a big— let me search ya
And find out how hard I gotta work ya
​ti esrever dna ti pilf ,nwod gniht ym tuP
​ti esrever dna ti pilf ,nwod gniht ym tuP (C'mon)

[Outro]
To my fellas (Ooh, good God)
I like the way you work that (Uh-huh, la-la-la-la)
To my ladies (Woo)
You sure know how to work that (Good God)42Embed
[Intro]
DJ, please pick up your phone, I'm on the request line
This is a Missy Elliott one-time exclusive (C'mon)

[Chorus]
Is it worth it? Let me work it
I put my thing down, flip it and reverse it
​ti esrever dna ti pilf ,nwod gniht ym tuP
​ti esrever dna ti pilf ,nwod gniht ym tuP
If you got a big— let me search ya
And find out how hard I gotta work ya
​ti esrever dna ti pilf ,nwod gniht ym tuP
​ti esrever dna ti pilf ,nwod gniht ym tuP (C'mon)

[Verse 1]
I'd like to get to know ya so I could show ya
Put the pussy on ya like I told ya
Give me all your numbers so I can phone ya
Your girl acting stank, then call me over
Not on the bed, lay me on your sofa
Call before you come, I need to shave my chocha
You do or you don't or you will or won't ya?
Go downtown and eat it like a vulture
See my hips and my tips, don't ya?
See my ass and my lips, don't ya?
Lost a few pounds and my waist for ya
This the kind of beat that go ra-ta-ta
Ra-ta-ta-ta-ta-ta-ta-ta-ta-ta
Sex me so good I say blah-blah-blah
Work it, I need a glass of water
Boy, oh boy, it's good to know ya (C'mon)

[Chorus]
Is it worth it? Let me work it
I put my thing down, flip it and reverse it
​ti esrever dna ti pilf ,nwod gniht ym tuP
​ti esrever dna ti pilf ,nwod gniht ym tuP
If you got a big— let me search ya
And find out how hard I gotta work ya
​ti esrever dna ti pilf ,nwod gniht ym tuP
​ti esrever dna ti pilf ,nwod gniht ym tuP (C'mon)

[Verse 2]
If you a fly gal, get your nails done
Get a pedicure, get your hair did
Boy, lift it up, let's make a toast-a
Let's get drunk, that's gonna bring us closer (Okay)
Don't I look like a Halle Berry poster?
See the Belvedere playing tricks on ya (Ah)
Girlfriend wanna be like me, never
You won't find a bitch that's even better (Ah)
I make you hot as Las Vegas weather
Listen up close while I take it backwards
​sdrawkcab ti ekat ot ekil yssiM yaw eht hctaW
I'm not a prostitute, but I could give you what you want
I love your braids and your mouth full of fronts
Love the way my ass go ba-bum-bum-bum-bum (Huh)
Keep your eyes on my ba-bum-bum-bum-bum-bum (Okay)
You think you can handle this? Ga-dunk-a-dunk-dunk (Woo)
Take my thong off and my ass go boom (Ugh)
Cut the lights on so you see what I could do (C'mon)

[Chorus]
Is it worth it? Let me work it
I put my thing down, flip it and reverse it
​ti esrever dna ti pilf ,nwod gniht ym tuP
​ti esrever dna ti pilf ,nwod gniht ym tuP (Ooh)
If you got a big— let me search ya
And find out how hard I gotta work ya
​ti esrever dna ti pilf ,nwod gniht ym tuP (Huh)
​ti esrever dna ti pilf ,nwod gniht ym tuP (C'mon, c'mon)

[Bridge]
Boys, boys, all type of boys
Black, white, Puerto Rican, Chinese boys (C'mon)
Why-thai, thai-o-toy-o-thai-thai
Why-thai, thai-o-toy-o-thai-thai (C'mon)
Girls, girls, get that cash
If it's nine to five or shaking your ass (Aha)
Ain't no shame, ladies do your thing (C'mon)
Just make sure you ahead of the game

[Verse 3]
Just 'cause I got a lot of fame super
Prince couldn't get me change my name, papa
Kunta Kinte a slave again, no sir
Picture Blacks saying, “Oh yes-a, massa”
Picture Lil' Kim dating a pastor
Minute man, Big Red could outlast ya
Who is the best? I don't have to ask ya
When I come out, you won't even matter (Ugh)
Why you act dumb like, yeah, duh?
So you act dumb like, uh, duh
As the drummer boy go ba-rom-pop-pom-pom (Ooh)
Give you some-some-some of this cinna-bun (C'mon)

[Chorus]
Is it worth it? Let me work it
I put my thing down, flip it and reverse it
​ti esrever dna ti pilf ,nwod gniht ym tuP
​ti esrever dna ti pilf ,nwod gniht ym tuP (Ooh)
If you got a big— let me search ya
And find out how hard I gotta work ya
​ti esrever dna ti pilf ,nwod gniht ym tuP
​ti esrever dna ti pilf ,nwod gniht ym tuP (C'mon)

[Outro]
To my fellas (Ooh, good God)
I like the way you work that (Uh-huh, la-la-la-la)
To my ladies (Woo)
You sure know how to work that (Good God)
74 ContributorsWTF (Where They From) Lyrics[Produced by Pharrell]
[Intro]

[Hook: Missy Elliott (Pharrell)]
(Shorty what?)
The dance that you doing is dumb
How they do it where you from? (Ayy!, Triflin'!)
Stickin' out your tongue
Girl, but you know you're too young
A bunch of girls do it and the shit look fun
That's how they do it where we from (Ayy!)
You know it don't start till one
That's how they do it where they from

[Verse 1: Missy Elliott]
I'm so faded, no exaggeration (What?)
Backs breakin' like a percolation (What?)
Boys to the yard for some hip spankin'
Where you make it drop down like you in the matrix (Yeah!)
Can't take it, them chicks been fakin' (What?)
Y'all still sleep, better stay awakened (What?)
Hot new dance for the hood to make it
Make the donk move fast, make them think you drinkin' (Yeah!)
Head to the floor don't collect that though (What?)
You better huddle up cause the beat's so cold (Huh?)
Pop that, pop that, cock and reload (Huh?)
This another hit, I got an ace in the hole (What?)
Boys on my back, playa, did you peep that?
You got a small stack, playa, you can keep that (Huh?)
I'm a Big Mac make you wanna eat that
Like m-m-m-m-m, yak it to the yak (Yeah?)
Junk in the trunk make you pumps in the bump
Girls wanna have fun make you stickin' out your tongue (What?)
See Missy Elliott LiveGet tickets as low as $236You might also like[Hook: Missy Elliott]
Shorty what?
The dance that you doing is dumb
How they do it where you from?
Stickin' out your tongue girl
But you know you're too young
A bunch of girls do it and the shit look fun
That's how they do it where we from
You know it don't start till one
That's how they do it where they from

[Verse 2: Pharrell]
I come into this bitch like liquid
Drip, drip, then the business
Click, click, get your picture
Hermés Trismegistus
Witness and get lifted
Basic, nigga I was born in the basement
Shape shift, nigga, I think like a spaceship
False, oh-nah-nah-nah
I am so different than y'all, so far apart
The way that I balance the bars
I never fall, and if I do I just call
The almighty yellow star, God
Lyrically I'm Optimus Prime
The car I drive; La FER-RAR-I
When I go by, smoke in your eyes
So open your eyes, the joke's on you guys
And you ain't gotta be a mason to see through
Some of this shit on occasion
[Hook: Missy Elliott]
Shorty what?
The dance that you doing is dumb
How they do it where you from?
Stickin' out your tongue, girl
But you know you're too young
A bunch of girls do it and the shit look fun
That's how they do it where we from
You know it don't start till one
That's how they do it where they from

[Verse 3: Missy Elliott]
I'm like kak-a-rak-a-rak-rak-a-rak-a-rak
Make a new track, make 'em fall on they crack
Give 'em a slap, appetizer and smack
I'm so fat in the back, make the boys all collapse
Yeah, when I rap they be all on my jack
Boys wanna jump on this pussy cat (Prrrr)
Got a new idea, let me switch it
Man, I'm so futuristic
Big lips and big, big, big hips
Body be thick like a biscuit
Different, rippin' shit, microphone grippin' it
Gettin' these Benjamins, new car, whippin' it
Uh, I'm so far ahead of ya'll, man I'm on top of the stars
I don't care none of you are, blah-blah-blah-blah
You best to go rewrite your bars
[Outro Missy Elliott & (Pharrell)]
Shawty what?
How they do it where you from? (Triflin'!)
How they do it where you from?
That's how they do it where we from
That's how they do it where they from
Shawty what?
How they do it where you from? (Hey!)
How they do it where you from?
That's how they do it where we from
That's how they do it where they from89Embed
[Produced by Pharrell]
[Intro]

[Hook: Missy Elliott (Pharrell)]
(Shorty what?)
The dance that you doing is dumb
How they do it where you from? (Ayy!, Triflin'!)
Stickin' out your tongue
Girl, but you know you're too young
A bunch of girls do it and the shit look fun
That's how they do it where we from (Ayy!)
You know it don't start till one
That's how they do it where they from

[Verse 1: Missy Elliott]
I'm so faded, no exaggeration (What?)
Backs breakin' like a percolation (What?)
Boys to the yard for some hip spankin'
Where you make it drop down like you in the matrix (Yeah!)
Can't take it, them chicks been fakin' (What?)
Y'all still sleep, better stay awakened (What?)
Hot new dance for the hood to make it
Make the donk move fast, make them think you drinkin' (Yeah!)
Head to the floor don't collect that though (What?)
You better huddle up cause the beat's so cold (Huh?)
Pop that, pop that, cock and reload (Huh?)
This another hit, I got an ace in the hole (What?)
Boys on my back, playa, did you peep that?
You got a small stack, playa, you can keep that (Huh?)
I'm a Big Mac make you wanna eat that
Like m-m-m-m-m, yak it to the yak (Yeah?)
Junk in the trunk make you pumps in the bump
Girls wanna have fun make you stickin' out your tongue (What?)

[Hook: Missy Elliott]
Shorty what?
The dance that you doing is dumb
How they do it where you from?
Stickin' out your tongue girl
But you know you're too young
A bunch of girls do it and the shit look fun
That's how they do it where we from
You know it don't start till one
That's how they do it where they from

[Verse 2: Pharrell]
I come into this bitch like liquid
Drip, drip, then the business
Click, click, get your picture
Hermés Trismegistus
Witness and get lifted
Basic, nigga I was born in the basement
Shape shift, nigga, I think like a spaceship
False, oh-nah-nah-nah
I am so different than y'all, so far apart
The way that I balance the bars
I never fall, and if I do I just call
The almighty yellow star, God
Lyrically I'm Optimus Prime
The car I drive; La FER-RAR-I
When I go by, smoke in your eyes
So open your eyes, the joke's on you guys
And you ain't gotta be a mason to see through
Some of this shit on occasion

[Hook: Missy Elliott]
Shorty what?
The dance that you doing is dumb
How they do it where you from?
Stickin' out your tongue, girl
But you know you're too young
A bunch of girls do it and the shit look fun
That's how they do it where we from
You know it don't start till one
That's how they do it where they from

[Verse 3: Missy Elliott]
I'm like kak-a-rak-a-rak-rak-a-rak-a-rak
Make a new track, make 'em fall on they crack
Give 'em a slap, appetizer and smack
I'm so fat in the back, make the boys all collapse
Yeah, when I rap they be all on my jack
Boys wanna jump on this pussy cat (Prrrr)
Got a new idea, let me switch it
Man, I'm so futuristic
Big lips and big, big, big hips
Body be thick like a biscuit
Different, rippin' shit, microphone grippin' it
Gettin' these Benjamins, new car, whippin' it
Uh, I'm so far ahead of ya'll, man I'm on top of the stars
I don't care none of you are, blah-blah-blah-blah
You best to go rewrite your bars

[Outro Missy Elliott & (Pharrell)]
Shawty what?
How they do it where you from? (Triflin'!)
How they do it where you from?
That's how they do it where we from
That's how they do it where they from
Shawty what?
How they do it where you from? (Hey!)
How they do it where you from?
That's how they do it where we from
That's how they do it where they from
66 ContributorsTranslationsRomanizationGet Ur Freak On Lyrics[Intro]
これからみんなで めちゃくちゃ踊って 騒ごう 騒ごう
Headbanger
Hit me (Yeah)
Hit me (Hit me)
Hit me, hit me (Yeah)
Hit me
Give me some new shit (Yeah)
Give me some new shit (Yeah)
Give me some new shit (Yeah)
Give me some new shit

[Verse 1]
Missy be puttin' it down, I'm the hottest 'round
I told y'all mother— (Skrrt), y'all can't stop me now
Listen to me now, I'm lastin' twenty rounds
And if you want me, nigga, then come on, get me now
(Yes) Is you with me now? (Yes) Then biggie-biggie-bounce
(Yes) I know you dig the way I sw-sw-switch my style
(Holla) People, sing around
(Yes) Now, people, gather 'round (Yes), now, people, jump around

[Chorus]
(Go) Get your freak on (Go), get your freak on
(Go) Get your freak on (Go), get your freak on
(Go) Get your freak on (Go), get your freak on
(Go) Get your, get your, get your (Go), get your, get your freak on
(Go) Get your freak on (Go), get your freak on
(Go) Get your freak on (Go), get your freak on
(Go) Get your freak on (Go), get your freak on
(Go) Get your, get your, get your (Go), get your, get your freak on
See Missy Elliott LiveGet tickets as low as $236You might also like[Verse 2]
Who's that bitch? People you know (Yes)
Me and Timbaland been hot since twenty years ago (Yes)
What the dealio? Now what the drilly, yo? (Yes)
You wanna battle me, then, nigga, let me know (Yes)
(Holla) Got to feel it, son
Let me throw you some (Maut mujhko)
(Yes) People, here I come (Yes), now sweat me when I'm done
(Yes) We got the radio shook like we got a gun

[Chorus]
(Go) Get your freak on (Go), get your freak on
(Go) Get your freak on (Go), get your freak on
(Go) Get your freak on (Go), get your freak on
(Go) Get your, get your, get your (Go), get your, get your freak on
(Go) Get your freak on (Go), get your freak on
(Go) Get your freak on (Go), get your freak on
(Go) Get your freak on (Go), get your freak on
(Go) Get your, get your, get your (Go), get your, get your freak on

[Verse 3]
Quiet (Shh), hush your mouth
Silence when I spit it out
In your face
Open your mouth, give you a taste
(Holla) Ain't no stoppin' me
Copywritten so don't copy me
Y'all do it sloppily
And y'all can't come close to me
(Yes) I know you feel me now (Yes), I know you hear me loud
(Yes) I scream it loud and proud (Yes), Missy gon' blow it down
(Yes) People gon' play me now (Yes) in and outta town
(Yes) 'Cause I'm the best around (Yes) with the crazy style
[Chorus]
(Go) Get your freak on (Go), get your freak on
(Go) Get your freak on (Go), get your freak on
(Go) Get your freak on (Go), get your freak on
(Go) Get your, get your, get your (Go), get your, get your freak on
(Go) Get your freak on (Go), get your freak on
(Go) Get your freak on (Go), get your freak on
(Go) Get your freak on (Go), get your freak on
(Go) Get your, get your, get your (Go), get your, get your freak on

[Outro]
一 二 三 四19Embed
[Intro]
これからみんなで めちゃくちゃ踊って 騒ごう 騒ごう
Headbanger
Hit me (Yeah)
Hit me (Hit me)
Hit me, hit me (Yeah)
Hit me
Give me some new shit (Yeah)
Give me some new shit (Yeah)
Give me some new shit (Yeah)
Give me some new shit

[Verse 1]
Missy be puttin' it down, I'm the hottest 'round
I told y'all mother— (Skrrt), y'all can't stop me now
Listen to me now, I'm lastin' twenty rounds
And if you want me, nigga, then come on, get me now
(Yes) Is you with me now? (Yes) Then biggie-biggie-bounce
(Yes) I know you dig the way I sw-sw-switch my style
(Holla) People, sing around
(Yes) Now, people, gather 'round (Yes), now, people, jump around

[Chorus]
(Go) Get your freak on (Go), get your freak on
(Go) Get your freak on (Go), get your freak on
(Go) Get your freak on (Go), get your freak on
(Go) Get your, get your, get your (Go), get your, get your freak on
(Go) Get your freak on (Go), get your freak on
(Go) Get your freak on (Go), get your freak on
(Go) Get your freak on (Go), get your freak on
(Go) Get your, get your, get your (Go), get your, get your freak on

[Verse 2]
Who's that bitch? People you know (Yes)
Me and Timbaland been hot since twenty years ago (Yes)
What the dealio? Now what the drilly, yo? (Yes)
You wanna battle me, then, nigga, let me know (Yes)
(Holla) Got to feel it, son
Let me throw you some (Maut mujhko)
(Yes) People, here I come (Yes), now sweat me when I'm done
(Yes) We got the radio shook like we got a gun

[Chorus]
(Go) Get your freak on (Go), get your freak on
(Go) Get your freak on (Go), get your freak on
(Go) Get your freak on (Go), get your freak on
(Go) Get your, get your, get your (Go), get your, get your freak on
(Go) Get your freak on (Go), get your freak on
(Go) Get your freak on (Go), get your freak on
(Go) Get your freak on (Go), get your freak on
(Go) Get your, get your, get your (Go), get your, get your freak on

[Verse 3]
Quiet (Shh), hush your mouth
Silence when I spit it out
In your face
Open your mouth, give you a taste
(Holla) Ain't no stoppin' me
Copywritten so don't copy me
Y'all do it sloppily
And y'all can't come close to me

## Get Specific Song and Lyrics By a Specific Artist

To get the song lyrics from a specific artist, you can use the method `.search_song()`

In [36]:
song = LyricsGenius.search_song("Missy Elliott", "Work It")

Searching for "Missy Elliott" by Work It...
Done.

In [38]:
print(song.lyrics)

127 ContributorsWork It Lyrics[Intro]
DJ, please pick up your phone, I'm on the request line
This is a Missy Elliott one-time exclusive (C'mon)

[Chorus]
Is it worth it? Let me work it
I put my thing down, flip it and reverse it
​ti esrever dna ti pilf ,nwod gniht ym tuP
​ti esrever dna ti pilf ,nwod gniht ym tuP
If you got a big— let me search ya
And find out how hard I gotta work ya
​ti esrever dna ti pilf ,nwod gniht ym tuP
​ti esrever dna ti pilf ,nwod gniht ym tuP (C'mon)

[Verse 1]
I'd like to get to know ya so I could show ya
Put the pussy on ya like I told ya
Give me all your numbers so I can phone ya
Your girl acting stank, then call me over
Not on the bed, lay me on your sofa
Call before you come, I need to shave my chocha
You do or you don't or you will or won't ya?
Go downtown and eat it like a vulture
See my hips and my tips, don't ya?
See my ass and my lips, don't ya?
Lost a few pounds and my waist for ya
This the kind of beat that go ra-ta-ta
Ra-ta-ta-ta-ta-ta-ta-ta-ta-ta
Sex me so good I say blah-blah-blah
Work it, I need a glass of water
Boy, oh boy, it's good to know ya (C'mon)
See Missy Elliott LiveGet tickets as low as $236You might also like[Chorus]
Is it worth it? Let me work it
I put my thing down, flip it and reverse it
​ti esrever dna ti pilf ,nwod gniht ym tuP
​ti esrever dna ti pilf ,nwod gniht ym tuP
If you got a big— let me search ya
And find out how hard I gotta work ya
​ti esrever dna ti pilf ,nwod gniht ym tuP
​ti esrever dna ti pilf ,nwod gniht ym tuP (C'mon)

[Verse 2]
If you a fly gal, get your nails done
Get a pedicure, get your hair did
Boy, lift it up, let's make a toast-a
Let's get drunk, that's gonna bring us closer (Okay)
Don't I look like a Halle Berry poster?
See the Belvedere playing tricks on ya (Ah)
Girlfriend wanna be like me, never
You won't find a bitch that's even better (Ah)
I make you hot as Las Vegas weather
Listen up close while I take it backwards
​sdrawkcab ti ekat ot ekil yssiM yaw eht hctaW
I'm not a prostitute, but I could give you what you want
I love your braids and your mouth full of fronts
Love the way my ass go ba-bum-bum-bum-bum (Huh)
Keep your eyes on my ba-bum-bum-bum-bum-bum (Okay)
You think you can handle this? Ga-dunk-a-dunk-dunk (Woo)
Take my thong off and my ass go boom (Ugh)
Cut the lights on so you see what I could do (C'mon)
[Chorus]
Is it worth it? Let me work it
I put my thing down, flip it and reverse it
​ti esrever dna ti pilf ,nwod gniht ym tuP
​ti esrever dna ti pilf ,nwod gniht ym tuP (Ooh)
If you got a big— let me search ya
And find out how hard I gotta work ya
​ti esrever dna ti pilf ,nwod gniht ym tuP (Huh)
​ti esrever dna ti pilf ,nwod gniht ym tuP (C'mon, c'mon)

[Bridge]
Boys, boys, all type of boys
Black, white, Puerto Rican, Chinese boys (C'mon)
Why-thai, thai-o-toy-o-thai-thai
Why-thai, thai-o-toy-o-thai-thai (C'mon)
Girls, girls, get that cash
If it's nine to five or shaking your ass (Aha)
Ain't no shame, ladies do your thing (C'mon)
Just make sure you ahead of the game

[Verse 3]
Just 'cause I got a lot of fame super
Prince couldn't get me change my name, papa
Kunta Kinte a slave again, no sir
Picture Blacks saying, “Oh yes-a, massa”
Picture Lil' Kim dating a pastor
Minute man, Big Red could outlast ya
Who is the best? I don't have to ask ya
When I come out, you won't even matter (Ugh)
Why you act dumb like, yeah, duh?
So you act dumb like, uh, duh
As the drummer boy go ba-rom-pop-pom-pom (Ooh)
Give you some-some-some of this cinna-bun (C'mon)
[Chorus]
Is it worth it? Let me work it
I put my thing down, flip it and reverse it
​ti esrever dna ti pilf ,nwod gniht ym tuP
​ti esrever dna ti pilf ,nwod gniht ym tuP (Ooh)
If you got a big— let me search ya
And find out how hard I gotta work ya
​ti esrever dna ti pilf ,nwod gniht ym tuP
​ti esrever dna ti pilf ,nwod gniht ym tuP (C'mon)

[Outro]
To my fellas (Ooh, good God)
I like the way you work that (Uh-huh, la-la-la-la)
To my ladies (Woo)
You sure know how to work that (Good God)42Embed
[Intro]
DJ, please pick up your phone, I'm on the request line
This is a Missy Elliott one-time exclusive (C'mon)

[Chorus]
Is it worth it? Let me work it
I put my thing down, flip it and reverse it
​ti esrever dna ti pilf ,nwod gniht ym tuP
​ti esrever dna ti pilf ,nwod gniht ym tuP
If you got a big— let me search ya
And find out how hard I gotta work ya
​ti esrever dna ti pilf ,nwod gniht ym tuP
​ti esrever dna ti pilf ,nwod gniht ym tuP (C'mon)

[Verse 1]
I'd like to get to know ya so I could show ya
Put the pussy on ya like I told ya
Give me all your numbers so I can phone ya
Your girl acting stank, then call me over
Not on the bed, lay me on your sofa
Call before you come, I need to shave my chocha
You do or you don't or you will or won't ya?
Go downtown and eat it like a vulture
See my hips and my tips, don't ya?
See my ass and my lips, don't ya?
Lost a few pounds and my waist for ya
This the kind of beat that go ra-ta-ta
Ra-ta-ta-ta-ta-ta-ta-ta-ta-ta
Sex me so good I say blah-blah-blah
Work it, I need a glass of water
Boy, oh boy, it's good to know ya (C'mon)

[Chorus]
Is it worth it? Let me work it
I put my thing down, flip it and reverse it
​ti esrever dna ti pilf ,nwod gniht ym tuP
​ti esrever dna ti pilf ,nwod gniht ym tuP
If you got a big— let me search ya
And find out how hard I gotta work ya
​ti esrever dna ti pilf ,nwod gniht ym tuP
​ti esrever dna ti pilf ,nwod gniht ym tuP (C'mon)

[Verse 2]
If you a fly gal, get your nails done
Get a pedicure, get your hair did
Boy, lift it up, let's make a toast-a
Let's get drunk, that's gonna bring us closer (Okay)
Don't I look like a Halle Berry poster?
See the Belvedere playing tricks on ya (Ah)
Girlfriend wanna be like me, never
You won't find a bitch that's even better (Ah)
I make you hot as Las Vegas weather
Listen up close while I take it backwards
​sdrawkcab ti ekat ot ekil yssiM yaw eht hctaW
I'm not a prostitute, but I could give you what you want
I love your braids and your mouth full of fronts
Love the way my ass go ba-bum-bum-bum-bum (Huh)
Keep your eyes on my ba-bum-bum-bum-bum-bum (Okay)
You think you can handle this? Ga-dunk-a-dunk-dunk (Woo)
Take my thong off and my ass go boom (Ugh)
Cut the lights on so you see what I could do (C'mon)

[Chorus]
Is it worth it? Let me work it
I put my thing down, flip it and reverse it
​ti esrever dna ti pilf ,nwod gniht ym tuP
​ti esrever dna ti pilf ,nwod gniht ym tuP (Ooh)
If you got a big— let me search ya
And find out how hard I gotta work ya
​ti esrever dna ti pilf ,nwod gniht ym tuP (Huh)
​ti esrever dna ti pilf ,nwod gniht ym tuP (C'mon, c'mon)

[Bridge]
Boys, boys, all type of boys
Black, white, Puerto Rican, Chinese boys (C'mon)
Why-thai, thai-o-toy-o-thai-thai
Why-thai, thai-o-toy-o-thai-thai (C'mon)
Girls, girls, get that cash
If it's nine to five or shaking your ass (Aha)
Ain't no shame, ladies do your thing (C'mon)
Just make sure you ahead of the game

[Verse 3]
Just 'cause I got a lot of fame super
Prince couldn't get me change my name, papa
Kunta Kinte a slave again, no sir
Picture Blacks saying, “Oh yes-a, massa”
Picture Lil' Kim dating a pastor
Minute man, Big Red could outlast ya
Who is the best? I don't have to ask ya
When I come out, you won't even matter (Ugh)
Why you act dumb like, yeah, duh?
So you act dumb like, uh, duh
As the drummer boy go ba-rom-pop-pom-pom (Ooh)
Give you some-some-some of this cinna-bun (C'mon)

[Chorus]
Is it worth it? Let me work it
I put my thing down, flip it and reverse it
​ti esrever dna ti pilf ,nwod gniht ym tuP
​ti esrever dna ti pilf ,nwod gniht ym tuP (Ooh)
If you got a big— let me search ya
And find out how hard I gotta work ya
​ti esrever dna ti pilf ,nwod gniht ym tuP
​ti esrever dna ti pilf ,nwod gniht ym tuP (C'mon)

[Outro]
To my fellas (Ooh, good God)
I like the way you work that (Uh-huh, la-la-la-la)
To my ladies (Woo)
You sure know how to work that (Good God)

# 4. Extra Exercise: Spotify

Author: Jun-Wei Liu (b09902009@ntu.edu.tw)

## Spotify API Setup

Log into the [dashboard](https://developer.spotify.com/dashboard) using your Spotify account. Create an app and select "Web API" for the question asking which APIs are you planning to use. You can fill out anything for "App Name", "App Description", and "Redirect URIs".


<img src="../images/Spotify-API-Create-App.png" width=100% >

Next step, you need the *access token*. The *access token* is a string which contains the credentials and permissions that can be used to access a given resource (e.g artists, albums or tracks) or user's data (e.g your profile or your playlists).

In order to request the access token you need to get your *Client ID* and *Client Secret*:

1. Click on the name of the app you have just created.
2. Click on the Settings button.
3. The Client ID can be found here. The Client Secret can be found behind the "View client secret" buttom.

In [ ]:
client_id = "INSERT YOUR CLIENT ID IN THESE QUOTATION MARKS"
client_secret = "INSERT YOUR CLIENT SECRET IN THESE QUOTATION MARKS"

Request the access token from the Spotify token endpoint URI. The token will be valid for 1 hours (3600 seconds). After that you will need to request again.

In [52]:
import requests

url = "https://accounts.spotify.com/api/token"
headers = {
    "Content-Type": "application/x-www-form-urlencoded"
}
data = {
    "grant_type": "client_credentials",
    "client_id": client_id,
    "client_secret": client_secret
}

response = requests.post(url, headers=headers, data=data)
access_token_json = response.json()
access_token_json

{'access_token': 'BQBh0B32z7KyKQfP4akM3GIenzP9mCJEJeIOvjlJ7kW4bIJ3ZP-sG28x9qcHMQ8eKSGGrQdt_8Og2t5DNpBZK8YP39uNkZSydE1lv4FOjvO5JzCLpuN0Bdi6JqqddbNCmIQ7kuEJtYk',
 'token_type': 'Bearer',
 'expires_in': 3600}

## How to I know what kinds of APIs to use and data to get?

That's when the [Spotify Web API Documentation](https://developer.spotify.com/documentation/web-api) comes in! The document lists all the functions for a variety of data and gives insturctions on how to use them to get the data you need.

The following sections will demonstrate a few example of commonly used ones, but remember always to check out the API document for usage and get more data for analysis!

Key things for API usage:
- What's the endpoint URL?
- What are the arguments needed for an API request?

## `Get Artist`

The "Get Artist" endpoint requests information about an artist.

According to the [API reference](https://developer.spotify.com/documentation/web-api/reference/get-an-artist):
- Endpoint URL: `https://api.spotify.com/v1/artists/{id}`
- Arguments:
    - `id`: the Spotify ID of the artist.

We will stick to the Missy Elliott example.

An easy way to get the Spotify ID of an artist is using the Spotify Desktop App:

1. Search the artist
1. Click on the three dots icon from the artist profile
1. Select Share > Copy link to artist. The Spotify ID is the value that comes right after the open.spotify.com/artist URI.

In [42]:
# Missy Elliott's Spotify artist ID
artist_id = "2wIVse2owClT7go1WT98tk"

# Send a GET request to the Spotify API
url = f"https://api.spotify.com/v1/artists/{artist_id}"
headers = {
    "Authorization": "Bearer " + access_token_json['access_token']
}
response = requests.get(url, headers=headers)
artist_data = response.json()
artist_data

{'external_urls': {'spotify': 'https://open.spotify.com/artist/2wIVse2owClT7go1WT98tk'},
 'followers': {'href': None, 'total': 2609470},
 'genres': ['hip hop'],
 'href': 'https://api.spotify.com/v1/artists/2wIVse2owClT7go1WT98tk',
 'id': '2wIVse2owClT7go1WT98tk',
 'images': [{'url': 'https://i.scdn.co/image/ab6761610000e5ebf6691f40d906f097e9fbaa4c',
   'height': 640,
   'width': 640},
  {'url': 'https://i.scdn.co/image/ab67616100005174f6691f40d906f097e9fbaa4c',
   'height': 320,
   'width': 320},
  {'url': 'https://i.scdn.co/image/ab6761610000f178f6691f40d906f097e9fbaa4c',
   'height': 160,
   'width': 160}],
 'name': 'Missy Elliott',
 'popularity': 70,
 'type': 'artist',
 'uri': 'spotify:artist:2wIVse2owClT7go1WT98tk'}

## `Get Playlist`

The "Get Playlist" endpoint gets a playlist owned by a Spotify user.

According to the [API reference](https://developer.spotify.com/documentation/web-api/reference/get-playlist):
- Endpoint URL: `https://api.spotify.com/v1/playlists/{playlist_id}`
- Arguments:
    - `playlist_id`: the Spotify ID of the playlist.

2024/11/27 Update: According to [Spotify](https://developer.spotify.com/blog/2024-11-27-changes-to-the-web-api), Web API will no longer be able to access "Algorithmic and Spotify-owned editorial playlists", but only user-owned playlists.

In [53]:
# "上班播放清單" playlist
# https://open.spotify.com/playlist/39oYWk8IhN8efflXzJWlHP
playlist_id = "39oYWk8IhN8efflXzJWlHP"

# Send a GET request to the Spotify API
url = f"https://api.spotify.com/v1/playlists/{playlist_id}"
headers = {
    "Authorization": "Bearer " + access_token_json['access_token']
}
response = requests.get(url, headers=headers)
playlist_data = response.json()
playlist_data

{'collaborative': False,
 'description': '',
 'external_urls': {'spotify': 'https://open.spotify.com/playlist/39oYWk8IhN8efflXzJWlHP'},
 'followers': {'href': None, 'total': 72},
 'href': 'https://api.spotify.com/v1/playlists/39oYWk8IhN8efflXzJWlHP',
 'id': '39oYWk8IhN8efflXzJWlHP',
 'images': [{'height': 640,
   'url': 'https://mosaic.scdn.co/640/ab67616d00001e021b6057e116a54d99708f77aeab67616d00001e023223b839ca09ffbe8b8edeedab67616d00001e02a16281143369ad78589a9747ab67616d00001e02a51c803d8ef69c3b7f8208e9',
   'width': 640},
  {'height': 300,
   'url': 'https://mosaic.scdn.co/300/ab67616d00001e021b6057e116a54d99708f77aeab67616d00001e023223b839ca09ffbe8b8edeedab67616d00001e02a16281143369ad78589a9747ab67616d00001e02a51c803d8ef69c3b7f8208e9',
   'width': 300},
  {'height': 60,
   'url': 'https://mosaic.scdn.co/60/ab67616d00001e021b6057e116a54d99708f77aeab67616d00001e023223b839ca09ffbe8b8edeedab67616d00001e02a16281143369ad78589a9747ab67616d00001e02a51c803d8ef69c3b7f8208e9',
   'width': 60}],
 'name': '上班播放清單',
 'owner': {'display_name': 'rxdkwjm5n2df6guewv2uarcvo',
  'external_urls': {'spotify': 'https://open.spotify.com/user/rxdkwjm5n2df6guewv2uarcvo'},
  'href': 'https://api.spotify.com/v1/users/rxdkwjm5n2df6guewv2uarcvo',
  'id': 'rxdkwjm5n2df6guewv2uarcvo',
  'type': 'user',
  'uri': 'spotify:user:rxdkwjm5n2df6guewv2uarcvo'},
 'primary_color': None,
 'public': True,
 'snapshot_id': 'AAAHK8IyjsPJLQMSGboAtiBNTfsRNtiL',
 'tracks': {'href': 'https://api.spotify.com/v1/playlists/39oYWk8IhN8efflXzJWlHP/tracks?offset=0&limit=100',
  'items': [{'added_at': '2020-08-20T13:16:38Z',
    'added_by': {'external_urls': {'spotify': 'https://open.spotify.com/user/rxdkwjm5n2df6guewv2uarcvo'},
     'href': 'https://api.spotify.com/v1/users/rxdkwjm5n2df6guewv2uarcvo',
     'id': 'rxdkwjm5n2df6guewv2uarcvo',
     'type': 'user',
     'uri': 'spotify:user:rxdkwjm5n2df6guewv2uarcvo'},
    'is_local': False,
    'primary_color': None,
    'track': {'preview_url': None,
     'available_markets': ['TW'],
     'explicit': False,
     'type': 'track',
     'episode': False,
     'track': True,
     'album': {'available_markets': ['TW'],
      'type': 'album',
      'album_type': 'single',
      'href': 'https://api.spotify.com/v1/albums/4a4AczO0gVcMkAoqFXxPLA',
      'id': '4a4AczO0gVcMkAoqFXxPLA',
      'images': [{'url': 'https://i.scdn.co/image/ab67616d0000b273a51c803d8ef69c3b7f8208e9',
        'width': 640,
        'height': 640},
       {'url': 'https://i.scdn.co/image/ab67616d00001e02a51c803d8ef69c3b7f8208e9',
        'width': 300,
        'height': 300},
       {'url': 'https://i.scdn.co/image/ab67616d00004851a51c803d8ef69c3b7f8208e9',
        'width': 64,
        'height': 64}],
      'name': '《不能說的秘密》電影原聲帶',
      'release_date': '2007-08-13',
      'release_date_precision': 'day',
      'uri': 'spotify:album:4a4AczO0gVcMkAoqFXxPLA',
      'artists': [{'external_urls': {'spotify': 'https://open.spotify.com/artist/2elBjNSdBE2Y3f0j1mjrql'},
        'href': 'https://api.spotify.com/v1/artists/2elBjNSdBE2Y3f0j1mjrql',
        'id': '2elBjNSdBE2Y3f0j1mjrql',
        'name': 'Jay Chou',
        'type': 'artist',
        'uri': 'spotify:artist:2elBjNSdBE2Y3f0j1mjrql'}],
      'external_urls': {'spotify': 'https://open.spotify.com/album/4a4AczO0gVcMkAoqFXxPLA'},
      'total_tracks': 25},
     'artists': [{'external_urls': {'spotify': 'https://open.spotify.com/artist/2elBjNSdBE2Y3f0j1mjrql'},
       'href': 'https://api.spotify.com/v1/artists/2elBjNSdBE2Y3f0j1mjrql',
       'id': '2elBjNSdBE2Y3f0j1mjrql',
       'name': 'Jay Chou',
       'type': 'artist',
       'uri': 'spotify:artist:2elBjNSdBE2Y3f0j1mjrql'}],
     'disc_number': 1,
     'track_number': 25,
     'duration_ms': 296533,
     'external_ids': {'isrc': 'TWA470713001'},
     'external_urls': {'spotify': 'https://open.spotify.com/track/1SiXT84WGxFVr8Mg50DEt7'},
     'href': 'https://api.spotify.com/v1/tracks/1SiXT84WGxFVr8Mg50DEt7',
     'id': '1SiXT84WGxFVr8Mg50DEt7',
     'name': '不能說的秘密',
     'popularity': 50,
     'uri': 'spotify:track:1SiXT84WGxFVr8Mg50DEt7',
     'is_local': False},
    'video_thumbnail': {'url': None}},
   {'added_at': '2020-08-20T13:16:47Z',
    'added_by': {'external_urls': {'spotify': 'https://open.spotify.com/user/rxdkwjm5n2df6guewv2uarcvo'},
     'href': 'https://api.spotify.com/v1/users/rxdkwjm5n2df6guewv2uarcvo',
     'id': 'rxdkwjm5n2df6guewv2uarcvo',
     'type': 'user',
     'uri': 'spotify:user:rxdkwjm5n2df6guewv2uarcvo'},
    'is_local': False,
    'primary_color': None,
    'track': {'preview_url': None,
     'available_markets': ['AR',
      'AU',
      'AT',
      'BE',
      'BO',
      'BR',
      'BG',
      'CA',
      'CL',
      'CO',
      'CR',
      'CY',
      'CZ',
      'DK',
      'DO',
      'DE',
      'EC',
      'EE',
      'SV',
      'FI',
      'FR',
      'GR',
      'GT',
      'HN',
      'HK',
      'HU',
      'IS',
      'IE',
      'IT',
      'LV',
      'LT',
      'LU',
      'MY',
      'MT',
      'MX',
      'NL',
      'NZ',
      'NI',
      'NO',
      'PA',
      'PY',
      'PE',
      'PH',
      'PL',
      'PT',
      'SG',
      'SK',
      'ES',
      'SE',
      'CH',
      'TW',
      'TR',
      'UY',
      'US',
      'GB',
      'AD',
      'LI',
      'MC',
      'ID',
      'JP',
      'TH',
      'VN',
      'RO',
      'IL',
      'ZA',
      'SA',
      'AE',
      'BH',
      'QA',
      'OM',
      'KW',
      'EG',
      'MA',
      'DZ',
      'TN',
      'LB',
      'JO',
      'PS',
      'IN',
      'BY',
      'KZ',
      'MD',
      'UA',
      'AL',
      'BA',
      'HR',
      'ME',
      'MK',
      'RS',
      'SI',
      'KR',
      'BD',
      'PK',
      'LK',
      'GH',
      'KE',
      'NG',
      'TZ',
      'UG',
      'AG',
      'AM',
      'BS',
      'BB',
      'BZ',
      'BT',
      'BW',
      'BF',
      'CV',
      'CW',
      'DM',
      'FJ',
      'GM',
      'GE',
      'GD',
      'GW',
      'GY',
      'HT',
      'JM',
      'KI',
      'LS',
      'LR',
      'MW',
      'MV',
      'ML',
      'MH',
      'FM',
      'NA',
      'NR',
      'NE',
      'PW',
      'PG',
      'PR',
      'WS',
      'SM',
      'ST',
      'SN',
      'SC',
      'SL',
      'SB',
      'KN',
      'LC',
      'VC',
      'SR',
      'TL',
      'TO',
      'TT',
      'TV',
      'VU',
      'AZ',
      'BN',
      'BI',
      'KH',
      'CM',
      'TD',
      'KM',
      'GQ',
      'SZ',
      'GA',
      'GN',
      'KG',
      'LA',
      'MO',
      'MR',
      'MN',
      'NP',
      'RW',
      'TG',
      'UZ',
      'ZW',
      'BJ',
      'MG',
      'MU',
      'MZ',
      'AO',
      'CI',
      'DJ',
      'ZM',
      'CD',
      'CG',
      'IQ',
      'LY',
      'TJ',
      'VE',
      'ET',
      'XK'],
     'explicit': False,
     'type': 'track',
     'episode': False,
     'track': True,
     'album': {'available_markets': ['AR',
       'AU',
       'AT',
       'BE',
       'BO',
       'BR',
       'BG',
       'CA',
       'CL',
       'CO',
       'CR',
       'CY',
       'CZ',
       'DK',
       'DO',
       'DE',
       'EC',
       'EE',
       'SV',
       'FI',
       'FR',
       'GR',
       'GT',
       'HN',
       'HK',
       'HU',
       'IS',
       'IE',
       'IT',
       'LV',
       'LT',
       'LU',
       'MY',
       'MT',
       'MX',
       'NL',
       'NZ',
       'NI',
       'NO',
       'PA',
       'PY',
       'PE',
       'PH',
       'PL',
       'PT',
       'SG',
       'SK',
       'ES',
       'SE',
       'CH',
       'TW',
       'TR',
       'UY',
       'US',
       'GB',
       'AD',
       'LI',
       'MC',
       'ID',
       'JP',
       'TH',
       'VN',
       'RO',
       'IL',
       'ZA',
       'SA',
       'AE',
       'BH',
       'QA',
       'OM',
       'KW',
       'EG',
       'MA',
       'DZ',
       'TN',
       'LB',
       'JO',
       'PS',
       'IN',
       'BY',
       'KZ',
       'MD',
       'UA',
       'AL',
       'BA',
       'HR',
       'ME',
       'MK',
       'RS',
       'SI',
       'KR',
       'BD',
       'PK',
       'LK',
       'GH',
       'KE',
       'NG',
       'TZ',
       'UG',
       'AG',
       'AM',
       'BS',
       'BB',
       'BZ',
       'BT',
       'BW',
       'BF',
       'CV',
       'CW',
       'DM',
       'FJ',
       'GM',
       'GE',
       'GD',
       'GW',
       'GY',
       'HT',
       'JM',
       'KI',
       'LS',
       'LR',
       'MW',
       'MV',
       'ML',
       'MH',
       'FM',
       'NA',
       'NR',
       'NE',
       'PW',
       'PG',
       'PR',
       'WS',
       'SM',
       'ST',
       'SN',
       'SC',
       'SL',
       'SB',
       'KN',
       'LC',
       'VC',
       'SR',
       'TL',
       'TO',
       'TT',
       'TV',
       'VU',
       'AZ',
       'BN',
       'BI',
       'KH',
       'CM',
       'TD',
       'KM',
       'GQ',
       'SZ',
       'GA',
       'GN',
       'KG',
       'LA',
       'MO',
       'MR',
       'MN',
       'NP',
       'RW',
       'TG',
       'UZ',
       'ZW',
       'BJ',
       'MG',
       'MU',
       'MZ',
       'AO',
       'CI',
       'DJ',
       'ZM',
       'CD',
       'CG',
       'IQ',
       'LY',
       'TJ',
       'VE',
       'ET',
       'XK'],
      'type': 'album',
      'album_type': 'album',
      'href': 'https://api.spotify.com/v1/albums/1JEzXcEYuEFKKmo4mfMgC7',
      'id': '1JEzXcEYuEFKKmo4mfMgC7',
      'images': [{'url': 'https://i.scdn.co/image/ab67616d0000b273a16281143369ad78589a9747',
        'width': 640,
        'height': 640},
       {'url': 'https://i.scdn.co/image/ab67616d00001e02a16281143369ad78589a9747',
        'width': 300,
        'height': 300},
       {'url': 'https://i.scdn.co/image/ab67616d00004851a16281143369ad78589a9747',
        'width': 64,
        'height': 64}],
      'name': '學著愛',
      'release_date': '2014-12-19',
      'release_date_precision': 'day',
      'uri': 'spotify:album:1JEzXcEYuEFKKmo4mfMgC7',
      'artists': [{'external_urls': {'spotify': 'https://open.spotify.com/artist/5fEQLwq1BWWQNR8GzhOIvi'},
        'href': 'https://api.spotify.com/v1/artists/5fEQLwq1BWWQNR8GzhOIvi',
        'id': '5fEQLwq1BWWQNR8GzhOIvi',
        'name': 'Eric Chou',
        'type': 'artist',
        'uri': 'spotify:artist:5fEQLwq1BWWQNR8GzhOIvi'}],
      'external_urls': {'spotify': 'https://open.spotify.com/album/1JEzXcEYuEFKKmo4mfMgC7'},
      'total_tracks': 11},
     'artists': [{'external_urls': {'spotify': 'https://open.spotify.com/artist/5fEQLwq1BWWQNR8GzhOIvi'},
       'href': 'https://api.spotify.com/v1/artists/5fEQLwq1BWWQNR8GzhOIvi',
       'id': '5fEQLwq1BWWQNR8GzhOIvi',
       'name': 'Eric Chou',
       'type': 'artist',
       'uri': 'spotify:artist:5fEQLwq1BWWQNR8GzhOIvi'}],
     'disc_number': 1,
     'track_number': 2,
     'duration_ms': 260573,
     'external_ids': {'isrc': 'TWA471410001'},
     'external_urls': {'spotify': 'https://open.spotify.com/track/7zyYmIdjqqiX6kLryb7QBx'},
     'href': 'https://api.spotify.com/v1/tracks/7zyYmIdjqqiX6kLryb7QBx',
     'id': '7zyYmIdjqqiX6kLryb7QBx',
     'name': '以後別做朋友',
     'popularity': 58,
     'uri': 'spotify:track:7zyYmIdjqqiX6kLryb7QBx',
     'is_local': False},
    'video_thumbnail': {'url': None}},
   {'added_at': '2020-08-20T13:19:03Z',
    'added_by': {'external_urls': {'spotify': 'https://open.spotify.com/user/rxdkwjm5n2df6guewv2uarcvo'},
     'href': 'https://api.spotify.com/v1/users/rxdkwjm5n2df6guewv2uarcvo',
     'id': 'rxdkwjm5n2df6guewv2uarcvo',
     'type': 'user',
     'uri': 'spotify:user:rxdkwjm5n2df6guewv2uarcvo'},
    'is_local': False,
    'primary_color': None,
    'track': {'preview_url': None,
     'available_markets': ['AR',
      'AU',
      'AT',
      'BE',
      'BO',
      'BR',
      'BG',
      'CA',
      'CL',
      'CO',
      'CR',
      'CY',
      'CZ',
      'DK',
      'DO',
      'DE',
      'EC',
      'EE',
      'SV',
      'FI',
      'FR',
      'GR',
      'GT',
      'HN',
      'HK',
      'HU',
      'IS',
      'IE',
      'IT',
      'LV',
      'LT',
      'LU',
      'MY',
      'MT',
      'MX',
      'NL',
      'NZ',
      'NI',
      'NO',
      'PA',
      'PY',
      'PE',
      'PH',
      'PL',
      'PT',
      'SG',
      'SK',
      'ES',
      'SE',
      'CH',
      'TW',
      'TR',
      'UY',
      'US',
      'GB',
      'AD',
      'LI',
      'MC',
      'ID',
      'JP',
      'TH',
      'VN',
      'RO',
      'IL',
      'ZA',
      'SA',
      'AE',
      'BH',
      'QA',
      'OM',
      'KW',
      'EG',
      'MA',
      'DZ',
      'TN',
      'LB',
      'JO',
      'PS',
      'IN',
      'BY',
      'KZ',
      'MD',
      'UA',
      'AL',
      'BA',
      'HR',
      'ME',
      'MK',
      'RS',
      'SI',
      'KR',
      'BD',
      'PK',
      'LK',
      'GH',
      'KE',
      'NG',
      'TZ',
      'UG',
      'AG',
      'AM',
      'BS',
      'BB',
      'BZ',
      'BT',
      'BW',
      'BF',
      'CV',
      'CW',
      'DM',
      'FJ',
      'GM',
      'GE',
      'GD',
      'GW',
      'GY',
      'HT',
      'JM',
      'KI',
      'LS',
      'LR',
      'MW',
      'MV',
      'ML',
      'MH',
      'FM',
      'NA',
      'NR',
      'NE',
      'PW',
      'PG',
      'PR',
      'WS',
      'SM',
      'ST',
      'SN',
      'SC',
      'SL',
      'SB',
      'KN',
      'LC',
      'VC',
      'SR',
      'TL',
      'TO',
      'TT',
      'TV',
      'VU',
      'AZ',
      'BN',
      'BI',
      'KH',
      'CM',
      'TD',
      'KM',
      'GQ',
      'SZ',
      'GA',
      'GN',
      'KG',
      'LA',
      'MO',
      'MR',
      'MN',
      'NP',
      'RW',
      'TG',
      'UZ',
      'ZW',
      'BJ',
      'MG',
      'MU',
      'MZ',
      'AO',
      'CI',
      'DJ',
      'ZM',
      'CD',
      'CG',
      'IQ',
      'LY',
      'TJ',
      'VE',
      'ET',
      'XK'],
     'explicit': False,
     'type': 'track',
     'episode': False,
     'track': True,
     'album': {'available_markets': ['AR',
       'AU',
       'AT',
       'BE',
       'BO',
       'BR',
       'BG',
       'CA',
       'CL',
       'CO',
       'CR',
       'CY',
       'CZ',
       'DK',
       'DO',
       'DE',
       'EC',
       'EE',
       'SV',
       'FI',
       'FR',
       'GR',
       'GT',
       'HN',
       'HK',
       'HU',
       'IS',
       'IE',
       'IT',
       'LV',
       'LT',
       'LU',
       'MY',
       'MT',
       'MX',
       'NL',
       'NZ',
       'NI',
       'NO',
       'PA',
       'PY',
       'PE',
       'PH',
       'PL',
       'PT',
       'SG',
       'SK',
       'ES',
       'SE',
       'CH',
       'TW',
       'TR',
       'UY',
       'US',
       'GB',
       'AD',
       'LI',
       'MC',
       'ID',
       'JP',
       'TH',
       'VN',
       'RO',
       'IL',
       'ZA',
       'SA',
       'AE',
       'BH',
       'QA',
       'OM',
       'KW',
       'EG',
       'MA',
       'DZ',
       'TN',
       'LB',
       'JO',
       'PS',
       'IN',
       'BY',
       'KZ',
       'MD',
       'UA',
       'AL',
       'BA',
       'HR',
       'ME',
       'MK',
       'RS',
       'SI',
       'KR',
       'BD',
       'PK',
       'LK',
       'GH',
       'KE',
       'NG',
       'TZ',
       'UG',
       'AG',
       'AM',
       'BS',
       'BB',
       'BZ',
       'BT',
       'BW',
       'BF',
       'CV',
       'CW',
       'DM',
       'FJ',
       'GM',
       'GE',
       'GD',
       'GW',
       'GY',
       'HT',
       'JM',
       'KI',
       'LS',
       'LR',
       'MW',
       'MV',
       'ML',
       'MH',
       'FM',
       'NA',
       'NR',
       'NE',
       'PW',
       'PG',
       'PR',
       'WS',
       'SM',
       'ST',
       'SN',
       'SC',
       'SL',
       'SB',
       'KN',
       'LC',
       'VC',
       'SR',
       'TL',
       'TO',
       'TT',
       'TV',
       'VU',
       'AZ',
       'BN',
       'BI',
       'KH',
       'CM',
       'TD',
       'KM',
       'GQ',
       'SZ',
       'GA',
       'GN',
       'KG',
       'LA',
       'MO',
       'MR',
       'MN',
       'NP',
       'RW',
       'TG',
       'UZ',
       'ZW',
       'BJ',
       'MG',
       'MU',
       'MZ',
       'AO',
       'CI',
       'DJ',
       'ZM',
       'CD',
       'CG',
       'IQ',
       'LY',
       'TJ',
       'VE',
       'ET',
       'XK'],
      'type': 'album',
      'album_type': 'album',
      'href': 'https://api.spotify.com/v1/albums/63lCCebNDe20nxyCvFWk8g',
      'id': '63lCCebNDe20nxyCvFWk8g',
      'images': [{'url': 'https://i.scdn.co/image/ab67616d0000b2731b6057e116a54d99708f77ae',
        'width': 640,
        'height': 640},
       {'url': 'https://i.scdn.co/image/ab67616d00001e021b6057e116a54d99708f77ae',
        'width': 300,
        'height': 300},
       {'url': 'https://i.scdn.co/image/ab67616d000048511b6057e116a54d99708f77ae',
        'width': 64,
        'height': 64}],
      'name': '如果雨之後',
      'release_date': '2017-12-15',
      'release_date_precision': 'day',
      'uri': 'spotify:album:63lCCebNDe20nxyCvFWk8g',
      'artists': [{'external_urls': {'spotify': 'https://open.spotify.com/artist/5fEQLwq1BWWQNR8GzhOIvi'},
        'href': 'https://api.spotify.com/v1/artists/5fEQLwq1BWWQNR8GzhOIvi',
        'id': '5fEQLwq1BWWQNR8GzhOIvi',
        'name': 'Eric Chou',
        'type': 'artist',
        'uri': 'spotify:artist:5fEQLwq1BWWQNR8GzhOIvi'}],
      'external_urls': {'spotify': 'https://open.spotify.com/album/63lCCebNDe20nxyCvFWk8g'},
      'total_tracks': 10},
     'artists': [{'external_urls': {'spotify': 'https://open.spotify.com/artist/5fEQLwq1BWWQNR8GzhOIvi'},
       'href': 'https://api.spotify.com/v1/artists/5fEQLwq1BWWQNR8GzhOIvi',
       'id': '5fEQLwq1BWWQNR8GzhOIvi',
       'name': 'Eric Chou',
       'type': 'artist',
       'uri': 'spotify:artist:5fEQLwq1BWWQNR8GzhOIvi'}],
     'disc_number': 1,
     'track_number': 4,
     'duration_ms': 281200,
     'external_ids': {'isrc': 'TWA471715004'},
     'external_urls': {'spotify': 'https://open.spotify.com/track/6kabSi7XCHHGThNme6J2tL'},
     'href': 'https://api.spotify.com/v1/tracks/6kabSi7XCHHGThNme6J2tL',
     'id': '6kabSi7XCHHGThNme6J2tL',
     'name': '如果雨之後',
     'popularity': 57,
     'uri': 'spotify:track:6kabSi7XCHHGThNme6J2tL',
     'is_local': False},
    'video_thumbnail': {'url': None}},
   {'added_at': '2020-08-20T13:19:04Z',
    'added_by': {'external_urls': {'spotify': 'https://open.spotify.com/user/rxdkwjm5n2df6guewv2uarcvo'},
     'href': 'https://api.spotify.com/v1/users/rxdkwjm5n2df6guewv2uarcvo',
     'id': 'rxdkwjm5n2df6guewv2uarcvo',
     'type': 'user',
     'uri': 'spotify:user:rxdkwjm5n2df6guewv2uarcvo'},
    'is_local': False,
    'primary_color': None,
    'track': {'preview_url': None,
     'available_markets': ['AR',
      'AU',
      'AT',
      'BE',
      'BO',
      'BR',
      'BG',
      'CA',
      'CL',
      'CO',
      'CR',
      'CY',
      'CZ',
      'DK',
      'DO',
      'DE',
      'EC',
      'EE',
      'SV',
      'FI',
      'FR',
      'GR',
      'GT',
      'HN',
      'HK',
      'HU',
      'IS',
      'IE',
      'IT',
      'LV',
      'LT',
      'LU',
      'MY',
      'MT',
      'MX',
      'NL',
      'NZ',
      'NI',
      'NO',
      'PA',
      'PY',
      'PE',
      'PH',
      'PL',
      'PT',
      'SG',
      'SK',
      'ES',
      'SE',
      'CH',
      'TW',
      'TR',
      'UY',
      'US',
      'GB',
      'AD',
      'LI',
      'MC',
      'ID',
      'JP',
      'TH',
      'VN',
      'RO',
      'IL',
      'ZA',
      'SA',
      'AE',
      'BH',
      'QA',
      'OM',
      'KW',
      'EG',
      'MA',
      'DZ',
      'TN',
      'LB',
      'JO',
      'PS',
      'IN',
      'BY',
      'KZ',
      'MD',
      'UA',
      'AL',
      'BA',
      'HR',
      'ME',
      'MK',
      'RS',

We can, for example, list the artist and the *popularity* of each song in the playlist. According to the [API reference](https://developer.spotify.com/documentation/web-api/reference/get-playlist) (scroll down to the "Response" section), the definition fo *popularity* is as follows:

> The popularity of the track. The value will be between 0 and 100, with 100 being the most popular.
> The popularity of a track is a value between 0 and 100, with 100 being the most popular. The popularity is calculated by algorithm and is based, in the most part, on the total number of plays the track has had and how recent those plays are.
> Generally speaking, songs that are being played a lot now will have a higher popularity than songs that were played a lot in the past.

We can also use the artist id in the response to request again with the `Get Artist` endpoint to get the number of followers of the artists.

In [61]:
def get_artist_followers(artist_id):
    # Send a GET request to the Spotify API
    url = f"https://api.spotify.com/v1/artists/{artist_id}"
    headers = {
        "Authorization": "Bearer " + access_token_json['access_token']
    }
    response = requests.get(url, headers=headers)
    artist_data = response.json()
    return artist_data['followers']['total']


playlist_tracks = []
for track in playlist_data['tracks']['items']:
    track_name = track['track']['name']
    track_artist = track['track']['artists'][0]['name']
    track_popularity = track['track']['popularity']
    track_artist_followers = get_artist_followers(track['track']['artists'][0]['id'])
    playlist_tracks.append([track_name, track_artist, track_artist_followers, track_popularity])

playlist_df = pd.DataFrame(playlist_tracks)
playlist_df.columns = ['track_name', 'track_artist', 'track_artist_followers', 'track_popularity']
playlist_df

   track_name  track_artist  track_artist_followers  track_popularity
0      不能說的秘密      Jay Chou                 6655346                50
1      以後別做朋友     Eric Chou                 1626880                58
2       如果雨之後     Eric Chou                 1626880                57
3      最笨的人是我     Abin Fang                   26057                38
4      累了走了散了            六哲                   33320                 0
..        ...           ...                     ...               ...
95     BBIBBI            IU                 9046141                59
96   Blueming            IU                 9046141                60
97     Wolves  Selena Gomez                51867859                74
98        敞篷車       頑童Mj116                  276444                33
99         不安    Ada Zhuang                  155854                23

[100 rows x 4 columns]